### ISSUE TITLE
Lock inversion in 0.13-SNAPSHOT

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#1009]
02:47:27 12 PeerGroup$ChainDownloadSpeedCalculator.run: Error in speed calculator
com.google.common.util.concurrent.CycleDetectingLockFactory$PotentialDeadlockException: nioConnectionHandler -> peergroup, peergroup -> nioConnectionHandler
        at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:817)
        at org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator.calculate(PeerGroup.java:1548)
        at org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator.run(PeerGroup.java:1538)
        at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.CycleDetectingLockFactory$ExampleStackTrace: peergroup -> nioConnectionHandler
        at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:817)
        at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:138)
        at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:88)
        at org.bitcoinj.core.Peer.setBloomFilter(Peer.java:1580)
        at org.bitcoinj.core.Peer.setBloomFilter(Peer.java:1556)
        at org.bitcoinj.core.PeerGroup.handleNewPeer(PeerGroup.java:1282)
        at org.bitcoinj.core.PeerGroup$PeerStartupListener.onPeerConnected(PeerGroup.java:219)
        at org.bitcoinj.core.Peer$2.run(Peer.java:392)
        at org.bitcoinj.utils.Threading$2.execute(Threading.java:141)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:389)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
        ... 2 more

**Comment by mikehearn** [comment]
I found this stack trace in my lighthouse server logs. I don't see how it can happen, as this thread does not hold the nioConnectionHandler lock at this point in the code, so perhaps we are leaking a lock somehow. I will investigate a bit.
