### ISSUE TITLE
Failed precondition in Wallet.reorganize()

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1041]
Excerpt from the log:

```
10:58:25.588 [PeerGroup Thread] PeerGroup - Starting ...
10:58:25.630 [PeerGroup Thread] PeerGroup - Peer discovery took 22msec and returned 186 items
10:58:25.668 [PeerGroup Thread] PeerGroup - Waiting 59 msec before next connect attempt to [37.116.109.186]:8333
10:58:25.732 [PeerGroup Thread] PeerGroup - Attempting connection to [82.165.152.15]:8333     (0 connected, 1 pending, 6 max)
10:58:25.737 [PeerGroup Thread] PeerGroup - Attempting connection to [2001:1620:f00:282::2]:8333     (0 connected, 2 pending, 6 max)
10:58:25.741 [PeerGroup Thread] PeerGroup - Attempting connection to [2803:6900:1::117]:8333     (0 connected, 3 pending, 6 max)
10:58:25.747 [PeerGroup Thread] PeerGroup - Attempting connection to [37.116.109.186]:8333     (0 connected, 4 pending, 6 max)
10:58:25.750 [PeerGroup Thread] PeerGroup - Attempting connection to [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333     (0 connected, 5 pending, 6 max)
10:58:25.752 [PeerGroup Thread] PeerGroup - Attempting connection to [190.55.86.32]:8333     (0 connected, 6 pending, 6 max)
10:58:25.868 [NioClientManager] NioClientManager - Successfully connected to seed.bitcoin.sipa.be/2601:c6:c100:3a00:eca2:42ff:fe5e:b519:8333
10:58:25.911 [NioClientManager] Peer - Announcing to seed.bitcoin.sipa.be/2601:c6:c100:3a00:eca2:42ff:fe5e:b519:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:25.957 [NioClientManager] NioClientManager - Successfully connected to seed.bitnodes.io/2803:6900:1::117:8333
10:58:25.962 [NioClientManager] Peer - Announcing to seed.bitnodes.io/2803:6900:1::117:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:25.964 [NioClientManager] NioClientManager - Successfully connected to seed.bitcoinstats.com/37.116.109.186:8333
10:58:25.967 [NioClientManager] Peer - Announcing to seed.bitcoinstats.com/37.116.109.186:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:25.970 [NioClientManager] NioClientManager - Successfully connected to dnsseed.bitcoin.dashjr.org/2001:1620:f00:282::2:8333
10:58:25.976 [NioClientManager] Peer - Announcing to dnsseed.bitcoin.dashjr.org/2001:1620:f00:282::2:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:25.980 [NioClientManager] NioClientManager - Successfully connected to seed.bitnodes.io/190.55.86.32:8333
10:58:25.982 [NioClientManager] Peer - Announcing to seed.bitnodes.io/190.55.86.32:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:26.080 [NioClientManager] NioClientManager - Successfully connected to seed.bitcoin.sipa.be/82.165.152.15:8333
10:58:26.080 [NioClientManager] Peer - Announcing to seed.bitcoin.sipa.be/82.165.152.15:8333 as: /bitcoinj:0.13.1/Bitcoin Wallet:4.36/
10:58:26.141 [NioClientManager] Peer - Connected to 2601:c6:c100:3a00:eca2:42ff:fe5e:b519: version=70002, subVer='/Satoshi:0.10.0/', services=0x1, time=2015-07-19 10:58:25, blocks=366024
10:58:26.146 [NioClientManager] PeerGroup - [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333: New peer      (1 connected, 5 pending, 6 max)
10:58:26.149 [NioClientManager] PeerGroup - Setting download peer: [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333
10:58:27.173 [bitcoinj user thread] TransactionBroadcast - broadcastTransaction: We have 1 peers, adding 4c953dd48c58c9dd0d0a97737b9bce3b7307d1e17ecb96c6cdc311c2cf69ff47 to the memory pool
10:58:27.178 [bitcoinj user thread] TransactionBroadcast - Sending to 1 peers, will wait for 0, sending to: [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333
10:58:27.213 [NioClientManager] Peer - Connected to 2803:6900:1::117: version=70002, subVer='/Satoshi:0.10.2/', services=0x1, time=2015-07-19 10:57:58, blocks=366024
10:58:27.236 [NioClientManager] PeerGroup - [2803:6900:1::117]:8333: New peer      (2 connected, 4 pending, 6 max)
10:58:27.340 [NioClientManager] Peer - Connected to 82.165.152.15: version=70002, subVer='/Satoshi:0.11.0/', services=0x1, time=2015-07-19 10:58:27, blocks=366024
10:58:27.389 [NioClientManager] Peer - Connected to 2001:1620:f00:282::2: version=70002, subVer='/Satoshi:0.10.1/', services=0x1, time=2015-07-19 10:58:26, blocks=366024
10:58:27.442 [NioClientManager] Peer - Connected to 190.55.86.32: version=70002, subVer='/Satoshi:0.10.0/', services=0x1, time=2015-07-19 10:58:30, blocks=366024
10:58:27.574 [NioClientManager] PeerGroup - [2001:1620:f00:282::2]:8333: New peer      (3 connected, 3 pending, 6 max)
10:58:27.627 [NioClientManager] PeerGroup - [82.165.152.15]:8333: New peer      (4 connected, 2 pending, 6 max)
10:58:27.636 [NioClientManager] PeerGroup - [190.55.86.32]:8333: New peer      (5 connected, 1 pending, 6 max)
10:58:27.670 [main] AutosyncReceiver - got broadcast: Intent { act=android.intent.action.BOOT_COMPLETED flg=0x8000010 cmp=de.schildbach.wallet/.service.AutosyncReceiver (has extras) }
10:58:27.671 [main] WalletApplication - last used 0 minutes ago, rescheduling blockchain sync in roughly 15 minutes
10:58:28.369 [NioClientManager] AbstractBlockChain - Block forks the chain at height 364463/block 00000000000000000cf530b3346a39156f56eb9259e5d7fd97a6e9168ffaf91e, but it did not cause a reorganize:
000000000000000013db04c70163373449856f943ff337cfa1ba3509136d698f
10:58:28.371 [NioClientManager] Wallet - Received tx on a side chain for -0.11658508 BTC: 6f2320474839a59ef34eb4b1e49e45112ec11aa3512bdceef084309e3a50b27b [0] in block 000000000000000013db04c70163373449856f943ff337cfa1ba3509136d698f
10:58:28.391 [NioClientManager] WalletFiles - Saving wallet, last seen block is 364464/00000000000000000cf530b3346a39156f56eb9259e5d7fd97a6e9168ffaf91e
10:58:28.605 [NioClientManager] WalletFiles - Save completed in 208msec
10:58:28.606 [AsyncTask #3] Context - Performing thread fixup: you are accessing bitcoinj via a thread that has not had any context set on it.
10:58:28.607 [AsyncTask #3] Context - This error has been corrected for, but doing this makes your app less robust.
10:58:28.607 [AsyncTask #3] Context - You should use Context.propagate() or a ContextPropagatingThreadFactory.
10:58:28.608 [AsyncTask #3] Context - Please refer to the user guide for more information about this.
10:58:28.617 [NioClientManager] AbstractBlockChain - Block is causing a re-organize
10:58:28.618 [NioClientManager] AbstractBlockChain - Re-organize after split at height 364463
10:58:28.619 [NioClientManager] AbstractBlockChain - Old chain head: 000000000000000000b6e6aea7f7b9df64b513b6a5b542c409cab04f0baf2e1c
10:58:28.620 [NioClientManager] AbstractBlockChain - New chain head: 000000000000000012cc387c4ec277ac3905b2eae5e2e7acfdcc597cbddfcc6d
10:58:28.621 [NioClientManager] AbstractBlockChain - Split at block: 00000000000000000cf530b3346a39156f56eb9259e5d7fd97a6e9168ffaf91e
10:58:28.728 [NioClientManager] Wallet - Old part of chain (top to bottom):
10:58:28.740 [NioClientManager] Wallet -   000000000000000000b6e6aea7f7b9df64b513b6a5b542c409cab04f0baf2e1c
10:58:28.741 [NioClientManager] Wallet - New part of chain (top to bottom):
10:58:28.743 [NioClientManager] Wallet -   000000000000000012cc387c4ec277ac3905b2eae5e2e7acfdcc597cbddfcc6d
10:58:28.763 [NioClientManager] Wallet -   000000000000000013db04c70163373449856f943ff337cfa1ba3509136d698f
10:58:28.772 [NioClientManager] Wallet - depthToSubtract = 1
10:58:28.784 [NioClientManager] Wallet - Replaying block 000000000000000013db04c70163373449856f943ff337cfa1ba3509136d698f
10:58:28.785 [NioClientManager] Wallet -   tx 6f2320474839a59ef34eb4b1e49e45112ec11aa3512bdceef084309e3a50b27b
10:58:28.788 [NioClientManager] Wallet - Received tx for -0.11658508 BTC: 6f2320474839a59ef34eb4b1e49e45112ec11aa3512bdceef084309e3a50b27b [0] in block 000000000000000013db04c70163373449856f943ff337cfa1ba3509136d698f
10:58:28.794 [NioClientManager] Wallet -   tx 6f2320474839a59ef34eb4b1e49e45112ec11aa3512bdceef084309e3a50b27b ->unspent
10:58:28.798 [NioClientManager] PeerSocketHandler - [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333 - 
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[na:0.0]
	at org.bitcoinj.core.Wallet.addWalletTransaction(Wallet.java:2456) ~[na:0.0]
	at org.bitcoinj.core.Wallet.processTxFromBestChain(Wallet.java:2003) ~[na:0.0]
	at org.bitcoinj.core.Wallet.receive(Wallet.java:1826) ~[na:0.0]
	at org.bitcoinj.core.Wallet.reorganize(Wallet.java:4191) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:688) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:521) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:414) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308) ~[na:0.0]
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:165) ~[na:0.0]
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945) ~[na:0.0]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:342) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
10:58:28.809 [NioClientManager] WalletApplication - bitcoinj uncaught exception
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[na:0.0]
	at org.bitcoinj.core.Wallet.addWalletTransaction(Wallet.java:2456) ~[na:0.0]
	at org.bitcoinj.core.Wallet.processTxFromBestChain(Wallet.java:2003) ~[na:0.0]
	at org.bitcoinj.core.Wallet.receive(Wallet.java:1826) ~[na:0.0]
	at org.bitcoinj.core.Wallet.reorganize(Wallet.java:4191) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:688) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:521) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:414) ~[na:0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308) ~[na:0.0]
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:165) ~[na:0.0]
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945) ~[na:0.0]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:342) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
10:58:28.870 [NioClientManager] PeerGroup - [2601:c6:c100:3a00:eca2:42ff:fe5e:b519]:8333: Peer died      (4 connected, 1 pending, 6 max)
```

The rest of the log sees several attempts to go over that block but it all fails in the same way.

Note to myself: Josh

**Comment by schildbach** [comment]
The issue was already present in bitcoinj 0.12.

**Comment by mikehearn** [comment]
What version is this? Perhaps bcj should print its own version to the logs when PeerGroup starts.

**Comment by schildbach** [comment]
Well this particular log was taken with bitcoinj 0.13 but I see from the users issue reports that the problem started with 0.12.

**Comment by mikehearn** [comment]
I guess a wallet replay fixes things? Or not?

**Comment by schildbach** [comment]
Has fixed the users wallet, yes.
