### ISSUE TITLE
Exception when using Wallet Template and Tor

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1071]
On current master, I modified wallet-template / Main.java to bitcoin.useTor() when run on mainnet. I get:

```
18:13:14 23 PeerGroup$7.run: Starting ...
18:13:14 23 PeerGroup$7.run: Starting Tor/Orchid ...
18:13:14 23 TorClient.start: Starting Orchid (version: 1.0.0)
18:13:14 25 CircuitCreationTask.checkCircuitsForCreation: Cannot build circuits because we don't have enough directory information
18:13:14 24 DirectoryImpl.loadFromStore: Loading cached network information from disk
18:13:14 24 DirectoryImpl.loadFromStore: Loading certificates
18:13:14 24 DirectoryImpl.loadFromStore: Loading consensus
18:13:15 24 DirectoryImpl.loadFromStore: Loading microdescriptor cache
18:13:15 24 DirectoryImpl.loadFromStore: loading state file
18:13:16 26 DirectoryDownloadTask$DownloadRouterDescriptorsTask.run: Failed to download router descriptors: Request /tor/micro/d/fACEQHi1g5TuZJ/B4gfmFJMy03DyacxGkvz4QJBcUyM-CCluiLUg8MlwdfHpyk2CNmTzab2I3RxO29frqZOgNHo-08Ct92vMQj+Uz6JefBo077/6tjIeGany8vrYJ5R4OHI-CSfnPCrGmggvSxBe5tpViX3HNRcHL25Ol9l9TYAzlQA to directory (none) returned error code: 404 Not found
18:13:21 28 DirectoryDownloadTask$DownloadRouterDescriptorsTask.run: Failed to download router descriptors: Request /tor/micro/d/M72uun1b5lyv8xl0CLa0twfNcLwbSkiFL9yrd6cj2eo-8UgnIC4fE1bga8BkPU+GQcxTaAIcQzw6UTC28DIdfUQ-iB1SceqO62wu3/66mQBUwQvbR0zSIvNIjn0D1hKQgTg-vNCdrDODLazh/Y/342V+oIKEptmiqizmd7U9871zv8M to directory (none) returned error code: 404 Not found
18:13:23 23 PeerGroup$7.run: Tor ready
18:13:23 23 PeerGroup.maybeCheckForLocalhostPeer: Localhost peer not detected.
18:13:23 23 HttpDiscovery.getPeers: Requesting seeds from http://main.seed.vinumeris.com/peers
18:13:23 23 PeerGroup$3.go: Peer discovery failure
org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:95)
	at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:837)
	at org.bitcoinj.core.PeerGroup$3.go(PeerGroup.java:506)
	at org.bitcoinj.core.PeerGroup$3.run(PeerGroup.java:472)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
	at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28)
	at java.net.Socket.setSoTimeout(Socket.java:1141)
	at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:159)
	at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
	at com.squareup.okhttp.Connection.connect(Connection.java:152)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:84)
	... 11 more
18:13:23 23 PeerGroup$3.go: Peer discovery didn't provide us any more peers, will try again later.
18:13:25 23 HttpDiscovery.getPeers: Requesting seeds from http://main.seed.vinumeris.com/peers
18:13:25 23 PeerGroup$3.go: Peer discovery failure
org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:95)
	at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:837)
	at org.bitcoinj.core.PeerGroup$3.go(PeerGroup.java:506)
	at org.bitcoinj.core.PeerGroup$3.run(PeerGroup.java:472)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
	at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28)
	at java.net.Socket.setSoTimeout(Socket.java:1141)
	at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:159)
	at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
	at com.squareup.okhttp.Connection.connect(Connection.java:152)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:84)
	... 13 more
18:13:25 23 PeerGroup$3.go: Peer discovery didn't provide us any more peers, will try again later.
18:13:26 23 HttpDiscovery.getPeers: Requesting seeds from http://main.seed.vinumeris.com/peers
18:13:26 23 PeerGroup$3.go: Peer discovery failure
org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:95)
	at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:837)
	at org.bitcoinj.core.PeerGroup$3.go(PeerGroup.java:506)
	at org.bitcoinj.core.PeerGroup$3.run(PeerGroup.java:472)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
	at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28)
	at java.net.Socket.setSoTimeout(Socket.java:1141)
	at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:159)
	at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
	at com.squareup.okhttp.Connection.connect(Connection.java:152)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:84)
	... 13 more
18:13:26 23 PeerGroup$3.go: Peer discovery didn't provide us any more peers, will try again later.
18:13:28 23 HttpDiscovery.getPeers: Requesting seeds from http://main.seed.vinumeris.com/peers
18:13:28 23 PeerGroup$3.go: Peer discovery failure
org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:95)
	at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:837)
	at org.bitcoinj.core.PeerGroup$3.go(PeerGroup.java:506)
	at org.bitcoinj.core.PeerGroup$3.run(PeerGroup.java:472)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
	at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28)
	at java.net.Socket.setSoTimeout(Socket.java:1141)
	at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:159)
	at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
	at com.squareup.okhttp.Connection.connect(Connection.java:152)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:84)
	... 13 more
18:13:28 23 PeerGroup$3.go: Peer discovery didn't provide us any more peers, will try again later.
```

**Comment by mikehearn** [comment]
Somehow your build is not using the bitcoinj version of Orchid but the old pre-fork version. Line 28 in our version is a comment not a throw.

**Comment by schildbach** [comment]
Indeed, I had an old dependency. Sorry.
