### ISSUE TITLE
BIP 21 label and message does not allow all allowed characters

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoinj/bitcoinj#1083]
The constructor BitcoinURI(NetworkParameters params, String input) does not accept (for example) the space character.

```
   @Test
    public void testGood_Label_With_Unescaped_Space() throws BitcoinURIParseException {
        testObject = new BitcoinURI(MainNetParams.get(), BitcoinURI.BITCOIN_SCHEME + ":" + MAINNET_GOOD_ADDRESS
                + "?label=Hello World");
        assertEquals("Hello World", testObject.getLabel());
    }

    @Test
    public void testGood_Message_with_unescaped_space() throws BitcoinURIParseException {
        testObject = new BitcoinURI(MainNetParams.get(), BitcoinURI.BITCOIN_SCHEME + ":" + MAINNET_GOOD_ADDRESS
                + "?message=Hello World");
        assertEquals("Hello World", testObject.getMessage());
    }

```

Both these test cases generates the following output:

```
org.bitcoinj.uri.BitcoinURIParseException: Bad URI syntax
	at org.bitcoinj.uri.BitcoinURI.<init>(BitcoinURI.java:143)
	at org.bitcoinj.uri.BitcoinURITest.testGood_Label_With_Unescaped_Space(BitcoinURITest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 54: bitcoin:1KzTSfqjF2iKCduwz59nv2uqh1W2JsTxZH?label=Hello World
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parse(URI.java:3039)
	at java.net.URI.<init>(URI.java:595)
	at org.bitcoinj.uri.BitcoinURI.<init>(BitcoinURI.java:141)
```

This should actually be alright. There's nothing in BIP21 or RFC 3986 that states that spaces should be %-encoded (I think...). However in RFC 2396 (which java.net.URI implements), spaces must be %-encoded. I'm not sure what other differences there are.

**Comment by schildbach** [comment]
What exactly is your point?
I think it's safe to escape spaces. Btw. you can also use '+' for a space.

**Comment by kallerosenbaum** [comment]
The point is that bitcoinj-based wallets trying to parse for example 

    bitcoin:mskZSuyFdqRqSZFs2Vsv2oyveGvks6d8Nq?label=Hello World

will fail. So wallets based on bitcoinj can not make payments using URIs containg spaces.

It's perfectly fine to escape spaces or use '+', but it's not required.

**Comment by schildbach** [comment]
I vaguely remember we had this discussion a couple of months/years ago and we agreed to URI-encode properly. Yes, there were several user reports regarding this but it was fixed easily on their side.

**Comment by kallerosenbaum** [comment]
I'm not sure I follow. The problem occurs when, say, a merchant shows a bitcoin URI like

    bitcoin:1KzTSfqjF2iKCduwz59nv2uqh1W2JsTxZH?label=pizza slice

Then the customer using for example Hive or "Schildbach wallet" will not be able to pay, because her wallet will not parse the URI correctly. This is because BitcoinURI assumes it can use java.net.URI to parse it, which it can't, since java.net.URI implements another specification than the one BIP21 relies on.

**Comment by schildbach** [comment]
Sure, the pizza vendor should not do that. A working URL would be

bitcoin:1KzTSfqjF2iKCduwz59nv2uqh1W2JsTxZH?label=pizza+slice

**Comment by kallerosenbaum** [comment]
No, the BitcoinURI class should be able to parse "bitcoin:1KzTSfqjF2iKCduwz59nv2uqh1W2JsTxZH?label=pizza slice". It's a bit too much to demand that all merchants encode space with + because bitcoinj doesn't handle it correctly.

Don't you agree that this is a bug in BitcoinURI?

**Comment by schildbach** [comment]
I'm afraid I don't agree. URI encoding must be used. There is several references in BIP21 to that. URIs with plain spaces are invalid.

**Comment by kallerosenbaum** [comment]
I had misinterpreted RFC 3986 thinking that space is a valid character in URIs. Now after reading it again I see that this is NOT the case. Please close this bug. This means that I have to correct some examples in BIP121. Thank you for making me realize that.

**Comment by schildbach** [comment]
No worries (-:

**Comment by kallerosenbaum** [comment]
While we're at it: Why is '+' a valid encoding for ' ' (space) in bitcoin: URIs? Isn't that a URL encoding thing? There is nothing in RFC 3986 about that, nor in BIP21? What am I missing? And what distinguishes a '+'-encoded space from a literal '+' in the query part?

**Comment by schildbach** [comment]
If you want the '+' character, you need to escape it using %2b. I'm not sure about the standard at the moment.

**Comment by kallerosenbaum** [comment]
The standard says that + is a valid character. It's within the sub-delims set:

```
   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   query         = *( pchar / "/" / "?" )
   fragment      = *( pchar / "/" / "?" )
   pct-encoded   = "%" HEXDIG HEXDIG
   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   reserved      = gen-delims / sub-delims
   gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

So we should not use + to encode space. We should use %20 do encode space, nothing else unless it is explicitly stated in BIP21, which it's not.
