### ISSUE TITLE
Thread stuck in SPVBlockStore.get 

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoinj/bitcoinj#1084]
I run a tomcat server using with a web app using bitcoinj 0.13.2.

Every once in a while (after a few days, or weeks) the java process starts consuming 100% of a core. It turns out that this thread is constantly running:

```
  "NioClientManager" daemon prio=10 tid=0x00007fa438054000 nid=0x37c3 runnable [0x00007fa40ca2f000]
   java.lang.Thread.State: RUNNABLE
        at org.bitcoinj.store.SPVBlockStore.get(SPVBlockStore.java:215)
        at org.bitcoinj.core.BlockChain.getStoredBlockInCurrentScope(BlockChain.java:160)
        at org.bitcoinj.core.AbstractBlockChain.tryConnectingOrphans(AbstractBlockChain.java:810)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:418)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308)
        at org.bitcoinj.core.BlockChain.add(BlockChain.java:165)
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:342)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
        at java.lang.Thread.run(Thread.java:745)
```

I checked (in the above example of the problem) that nid=0x37c3 is the same as "top -H" displays as the thread (14275 decimal) consuming the cpu.

I've generated many (10-20) thread dumps and it was the exact line SPVBlockStore.java:215 in all of them.

The only way to "fix" this is to kill -9 the java process and restart it.

I've tried to analyze the code, but couldn't find anything obvious causing this. Maybe someone here could shed some light on this? Do you have any suggestions on how I could debug this further?

**Comment by ollekullberg** [comment]
For those who don't have the energy to check out 0.13.2, I've conveted the stacktrace to 0.14:

        at org.bitcoinj.core.BlockChain.getStoredBlockInCurrentScope(BlockChain.java:160)
        at org.bitcoinj.core.AbstractBlockChain.tryConnectingOrphans(AbstractBlockChain.java:897)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:472)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308)
        at org.bitcoinj.core.BlockChain.add(BlockChain.java:165)
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:975)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:372)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ollekullberg** [comment]
My first guess would be infinite loop, since the while does not have a "<" check:

            } while (cursor != startingPoint);

**Comment by mikehearn** [comment]
SPVBlockStore needs a rewrite, really. mmap is just way too flaky on different systems and it interacts badly with the java gc.
