### ISSUE TITLE
Precondition failure in Wallet.updateForSpends() and stuck payment

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1091]
On bitcoinj 0.13.2:

java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[na:0.0]
        at org.bitcoinj.core.Wallet.updateForSpends(Wallet.java:2099) ~[na:0.0]
        at org.bitcoinj.core.Wallet.processTxFromBestChain(Wallet.java:1990) ~[na:0.0]
        at org.bitcoinj.core.Wallet.receive(Wallet.java:1826) ~[na:0.0]
        at org.bitcoinj.core.Wallet.notifyTransactionIsInBlock(Wallet.java:1565) ~[na:0.0]
        at org.bitcoinj.core.AbstractBlockChain.informListenerForNewTransactions(AbstractBlockChain.java:595) ~[na:0.0]
        at org.bitcoinj.core.AbstractBlockChain.informListenersForNewBlock(AbstractBlockChain.java:537) ~[na:0.0]
        at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:478) ~[na:0.0]
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:414) ~[na:0.0]
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308) ~[na:0.0]
        at org.bitcoinj.core.BlockChain.add(BlockChain.java:165) ~[na:0.0]
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945) ~[na:0.0]
        at org.bitcoinj.core.Peer.processMessage(Peer.java:342) ~[na:0.0]
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) ~[na:0.0]
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) ~[na:0.0]
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) ~[na:0.0]
        at java.lang.Thread.run(Thread.java:841) ~[na:0.0]

The payment that is stuck is

Sends 0.00 BTC and receives 0.199 BTC, total value 0.199 BTC.
  d486cec4c7a89321a1f9dd5fd77744ddf8b5790f1018a71640b72eb00dc8022c: Seen by 1 peer. Pending/unconfirmed.
     in   PUSHDATA(72)[304502207b4a4a92523997b169fded89c08f63b5b921664992e61e8925c273797e9e38f4022100a3a8451e9efa69ee7fc0e3086a5bf81099774b3bd9068e56f160faa33f5847d201] PUSHDATA(33)[02a9a96fcbc8c14aebdf9d292e26ccd3205fd04bfdba7aab77f8d5ba3a732feb6a]
          outpoint:b8a75f255561632db2fd48ee300dbdb03fc078aed51d0909c28d11c453f25c9a:0
     out  DUP HASH160 PUSHDATA(20)[874b0727388fe42e7ed2eccace56aad7458ae448] EQUALVERIFY CHECKSIG 0.199 BTC Spent by 54c98f285041a3be901b260717ea73065f07ffa1bce96528dd796eb800cafde8

Sends 0.00 BTC and receives 0.199 BTC, total value 0.199 BTC.
  5fb4f87ce382db25c2bc5ee3c6678ace44084cae463af24d6e7c2d2f1f1fc2c8: Seen by 2 peers. Pending/unconfirmed.
     in   PUSHDATA(71)[304402207b4a4a92523997b169fded89c08f63b5b921664992e61e8925c273797e9e38f402205c57bae161059611803f1cf795a407ee213791aad64211e4ce7163e990ddf96f01] PUSHDATA(33)[02a9a96fcbc8c14aebdf9d292e26ccd3205fd04bfdba7aab77f8d5ba3a732feb6a] 0.20 BTC
          outpoint:b8a75f255561632db2fd48ee300dbdb03fc078aed51d0909c28d11c453f25c9a:0
     out  DUP HASH160 PUSHDATA(20)[874b0727388fe42e7ed2eccace56aad7458ae448] EQUALVERIFY CHECKSIG 0.199 BTC Spent by a23a9a4edb6c564f7891d64e47f2b4cc8cdcdd2b6b0b3d9d4ac20bbd416f2722
     fee  0.001 BTC

Yes that's two transactions because it has been malleated:

d486cec4c7a89321a1f9dd5fd77744ddf8b5790f1018a71640b72eb00dc8022c has been confirmed.
5fb4f87ce382db25c2bc5ee3c6678ace44084cae463af24d6e7c2d2f1f1fc2c8 has been double spent, so it should be marked as dead but it isn't.

The user has used "raise fee" a lot on top of these transactions, creating a chain of transactions but it should not matter regarding the confimation state of the above two transactions.

Full log attached.
[wallet.325249704.log.txt](https://github.com/bitcoinj/bitcoinj/files/7528/wallet.325249704.log.txt)

Note to myself: elmie

**Comment by schildbach** [comment]
Another case: jordan

**Comment by schildbach** [comment]
Another case: deborah

Another weirdness is if two pending txns double spend each other, both values count towards the balance. I know we can't know which of the two will make it into the chain, but showing a balance that is higher than it can ever be confuses users.
