### ISSUE TITLE
Problems running examples PrintPeers

### ISSUE THREAD

**Issue by mik3hall** [bitcoinj/bitcoinj#1109]
Same as first part of
 Trouble with Context on bitcoinj 0.13.2 #1093 
https://github.com/bitcoinj/bitcoinj/issues/1093

Exception in thread "main" java.lang.IllegalStateException: You must construct a Context object before using bitcoinj!
	at org.bitcoinj.core.Context.get(Context.java:83)
	at org.bitcoinj.core.Peer.<init>(Peer.java:227)
	at org.bitcoinj.core.Peer.<init>(Peer.java:193)
	at org.bitcoinj.core.Peer.<init>(Peer.java:174)
	at org.bitcoinj.examples.PrintPeers.main(PrintPeers.java:88)

Same fix worked...
Context.getOrCreate(MainNetParams.get());

**Comment by mik3hall** [comment]
I was thinking of making this a separate issue because I thought I had another instance. But so far I guess this just came up on PrintPeers.

Exception in thread "main" java.lang.IllegalStateException
	at org.bitcoinj.net.NioClientManager.openConnection(NioClientManager.java:150)
	at org.bitcoinj.examples.PrintPeers.main(PrintPeers.java:121)

Adding these...
        clientManager.startAsync();         
        clientManager.awaitRunning();         

after Line 83
NioClientManager clientManager = new NioClientManager();

seemed a workaround.

**Comment by tofutim** [comment]
Thats strange, I just ran into this a well. I'll try your work around.
