### ISSUE TITLE
Some wallets fail Precondition when trying to restore from seed.

### ISSUE THREAD

**Issue by jarlfr** [bitcoinj/bitcoinj#1169]
I'm following the steps as show in example, 
https://github.com/bitcoinj/bitcoinj/blob/master/examples/src/main/java/org/bitcoinj/examples/RestoreFromSeed.java 

Then, for some wallets, but not all, I get this error:
```java
RuntimeException while executing runnable org.bitcoinj.core.Peer$9@f266db3 with executor org.bitcoinj.utils.Threading$2@17a520cc
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at org.bitcoinj.core.Peer$9.run(Peer.java:1649)
	at org.bitcoinj.utils.Threading$2.execute(Threading.java:141)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at org.bitcoinj.core.Peer$PendingPing.complete(Peer.java:1428)
	at org.bitcoinj.core.Peer.processPong(Peer.java:1512)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:396)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schildbach** [comment]
So is this reproducable for specific wallets? Looking at the code, I doubt it. But if it's the case can you disclose one of these wallets (and your code)?

**Comment by jarlfr** [comment]
I checked briefly and guess somehow the the Peer.maybeRestartChainDownload is called twice before the ping() completes... but I have not spent any time on how/why.

* I depend on "0.14-SNAPSHOT"


* It's test coins so, you are free to try:

```java
String seedCode = "hedgehog scare behave wine soap yellow train better stem trigger dinosaur route";
Long creationtime = 1441065600L;
```

* Full code here, (just the modified example in bitcoinj linked above)
```java

import org.bitcoinj.core.BlockChain;
import org.bitcoinj.core.NetworkParameters;
import org.bitcoinj.core.PeerGroup;
import org.bitcoinj.core.Wallet;
import org.bitcoinj.core.listeners.DownloadProgressTracker;
import org.bitcoinj.net.discovery.DnsDiscovery;
import org.bitcoinj.params.TestNet3Params;
import org.bitcoinj.store.SPVBlockStore;
import org.bitcoinj.wallet.DeterministicSeed;

import java.io.File;
import java.util.Date;

public class RestoreFromSeed {

    public static void main(String[] args) throws Exception {
        NetworkParameters params = TestNet3Params.get();


        String seedCode = "hedgehog scare behave wine soap yellow train better stem trigger dinosaur route";
        String passphrase = "";
        Long creationtime = 1441065600L;

        DeterministicSeed seed = new DeterministicSeed(seedCode, null, passphrase, creationtime);

        Wallet wallet = Wallet.fromSeed(params, seed);

        System.out.println(wallet.toString());
        wallet.clearTransactions(0);
        File chainFile = new File("xrestore-from-seed.spvchain");
        if (chainFile.exists()) {
            chainFile.delete();
        }

        SPVBlockStore chainStore = new SPVBlockStore(params, chainFile);
        BlockChain chain = new BlockChain(params, chainStore);
        PeerGroup peers = new PeerGroup(params, chain);
        peers.addPeerDiscovery(new DnsDiscovery(params));

        chain.addWallet(wallet);
        peers.addWallet(wallet);

        DownloadProgressTracker bListener = new DownloadProgressTracker() {
            @Override
            public void doneDownload() {
                System.out.println("blockchain downloaded");
            }

            @Override
            protected void progress(double pct, int blocksSoFar, Date date) {
                super.progress(pct, blocksSoFar, date);
                System.out.println("" + ((int) pct) + " " + blocksSoFar + " " + date);
            }
        };

        peers.start();
        peers.startBlockChainDownload(bListener);

        bListener.await();

        System.out.println(wallet.toString());
        wallet.saveToFile(new File("xrestore-from-seed.wallet"));

        peers.stop();
    }
}

```

* Gives this before 97% complete:
```java
RuntimeException while executing runnable org.bitcoinj.core.Peer$9@306451a8 with executor org.bitcoinj.utils.Threading$2@ccaf109
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at org.bitcoinj.core.Peer$9.run(Peer.java:1649)
	at org.bitcoinj.utils.Threading$2.execute(Threading.java:141)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at org.bitcoinj.core.Peer$PendingPing.complete(Peer.java:1428)
	at org.bitcoinj.core.Peer.processPong(Peer.java:1512)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:396)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jarlfr** [comment]
I tried this on latest 0.15-SNAPSHOT, and at least this example downloads fine now.
