### ISSUE TITLE
Bit-flip check failed while getting a new receive address

### ISSUE THREAD

**Issue by langerhans** [bitcoinj/bitcoinj#1170]
I have been sent the following stacktrace by a user of my android wallet port. This seems to be related to the issue reported here on the mailing list: https://groups.google.com/forum/#!topic/bitcoinj/ztbzHqPaIro

```
java.lang.IllegalStateException: Bit-flip check failed: [2, 96, 61, -55, 88, 67, 79, 127, 102, -37, 60, 24, -99, 46, -96, -69, -128, -90, 82, 118, 22, 36, 79, 39, -95, 61, 14, 3, 41, -109, -55, -125, -126] vs [2, 25, -117, 6, -104, -59, -81, -64, 43, -29, 7, 24, -67, 3, 28, -89, 92, -45, 53, 58, 119, -116, 113, -83, 124, 33, -62, 94, 96, 19, -38, -7, -72]
at org.bitcoinj.wallet.DeterministicKeyChain.checkForBitFlip(DeterministicKeyChain.java:531)
at org.bitcoinj.wallet.DeterministicKeyChain.getKeys(DeterministicKeyChain.java:517)
at org.bitcoinj.wallet.KeyChainGroup.freshKeys(KeyChainGroup.java:231)
at org.bitcoinj.wallet.KeyChainGroup.freshKey(KeyChainGroup.java:210)
at org.bitcoinj.wallet.KeyChainGroup.freshAddress(KeyChainGroup.java:247)
at org.bitcoinj.core.Wallet.freshAddress(Wallet.java:460)
at org.bitcoinj.core.Wallet.freshReceiveAddress(Wallet.java:473)
at de.schildbach.wallet.ui.RequestCoinsFragment.onCreate(RequestCoinsFragment.java:177)
```

There, a log from wallet creation time was requested. I'll attach the log that was attached to the user's issue report, hope it helps to pinpoint this. This is the first time I have seen this exception.
[wallet.-1455375247.txt](https://github.com/bitcoinj/bitcoinj/files/104075/wallet.-1455375247.txt)

Let me know if you need anything else.

**Comment by schildbach** [comment]
Do you know what phone this was on?

**Comment by langerhans** [comment]
Looks like some unknown brand:

```
=== device info ===

Device Model: TCL S960
Android Version: 4.2.2
Board: TCL_S960
Brand: TCT
Device: DIABLOXPLUS
Display: Jelly Bean
Finger Print: TCT/TCL_S960/DIABLOXPLUS:4.2.2/JDQ39/vA3V-0:user/release-keys
Host: aclgcl-ubnt83
ID: JDQ39
Product: TCL_S960
Tags: release-keys
Time: 1398832551000
Type: user
User: zxliu
Configuration: {1.0 259mcc2mnc en ldltr sw360dp w360dp h615dp 480dpi nrml long port ?jrdtheme = 2 finger -keyb/v/h -nav/h skin=/system/framework/framework-res.apk s.74 font.defaultFontPath fontStylePackageName=defaultFontPacName}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=3.0, width=1080, height=1920, scaledDensity=3.0, xdpi=480.0, ydpi=480.0}
Memory Class: 128/512
```

**Comment by schildbach** [comment]
Hmm, when I see this error it's always on "no name" hardware. I wonder if this is simply caused by faulty hardware. I didn't see anything suspicious in the log either.

Let's keep collecting evidence in this ticket.

**Comment by billair** [comment]
Hello,
it happens to me today whole day on computer while developing ... everytime I call kit.wallet().freshReceiveAddress(), it creates address but return the error, temporarily I just putted there try/catch block and everything works fine now..
