### ISSUE TITLE
Failure when attempting to use pull-tests.jar with Core

### ISSUE THREAD

**Issue by droark** [bitcoinj/bitcoinj#1236]
Hello. I'm getting the following error when I run the following with Bitcoin Core (master branch, fully updated). This is with v0.13.6 of bitcoinj, compiled by myself on Ubuntu 15.10 using the latest upstream version of Maven (3.3.9) and Ubuntu's latest OpenJDK packages.

```
./configure --disable-silent-rules --disable-ccache --with-tests --with-comparison-tool=../bitcoind-comparisontool/pull-tests-8c6666f.jar
(...)
make check -j4
(...)
USAGE: bitcoinjBlockStoreLocation runExpensiveTests(1/0) [port=18444]
Exception in thread "main" java.lang.IllegalStateException: You must construct a Context object before using bitcoinj!
	at org.bitcoinj.core.Context.get(Context.java:77)
	at org.bitcoinj.core.Transaction.getConfidence(Transaction.java:1158)
	at org.bitcoinj.core.Block.parseTransactions(Block.java:228)
	at org.bitcoinj.core.Block.parse(Block.java:242)
	at org.bitcoinj.core.Message.<init>(Message.java:114)
	at org.bitcoinj.core.Message.<init>(Message.java:150)
	at org.bitcoinj.core.Block.<init>(Block.java:126)
	at org.bitcoinj.core.FullBlockTestGenerator.getBlocksToTest(FullBlockTestGenerator.java:1061)
	at org.bitcoinj.core.BitcoindComparisonTool.main(BitcoindComparisonTool.java:71)
2016-03-29 02:43:10 
```

Any ideas what might be happening here? I'm not a Java developer but I assume that the problem is [here](https://github.com/bitcoinj/bitcoinj/blob/v0.13.6/core/src/main/java/org/bitcoinj/core/Transaction.java#L1158). I assume the Context object doesn't exist? The code in the checkpointed pull-tests.jar I linked [does things differently](https://github.com/theuni/bitcoinj/blob/8c6666fa618b1c06b84ba6925f92bad4fa5145e1/core/src/main/java/com/google/bitcoin/core/Transaction.java#L1126).

Thanks!

**Comment by schildbach** [comment]
Can you add `Context ctx = new Context(params);` to BitcoindComparisonTool line 66 (after `params = RegTestParams.get()`) and try again? That issue was fixed on master but not on release-0.13.

**Comment by droark** [comment]
Hi. Thanks for the suggestion. That seemed to do the trick. I am getting an error during the tests.

```
10:55:07 1 BitcoindComparisonTool.main: ERROR: bitcoind had an empty mempool, but we expected some transactions on rule post-b82 tx resurrection
```

I'm new to interpreting the tests and am not sure what caused this one. Assuming I'm understanding things correctly, this means the version of Core that I ran (up-to-date master snapshot) had different behavior than what bitcoinj was expecting. Is this correct? Can somebody clarify?

Thanks.

**Comment by schildbach** [comment]
It's very likely there is some discrepancy between Core and full-validation bitcoinj. Afaik the code in bitcoinj hasn't progressed much since a couple of months and there was discussion to remove full validation entirely.

Yeah the database format changed a bit, all column names were lowercased. So if you want to keep the data, you need to manually rename the column names (or maybe switch it to case insensitive if that's possible).

**Comment by droark** [comment]
Thanks. I'm not entirely sure what you mean when talking about the DB, though. Which one, and how do I redo the data and such?

**Comment by schildbach** [comment]
I looked into the DB problem again and indeed the problem is the coinbase column does not exist. It was added with commit 90041661227049d858d6a318e9e13029f363cbd0, can you read the commit description?

**Comment by droark** [comment]
Ahhh, my head was on autopilot. Thanks.

For some reason, I can't seem to reproduce the DB error I mentioned earlier. The fixed 0.13.6 JAR seems to go through the process without complaints on both OS X and Linux. There are errors but that's another story.

Anyway, while it would be nice to submit a patch for 0.13, am I correct in assuming that 0.14 is nearing completion? I noticed that the code appears to have dropped the comparison tool. I'd like to see the tool survive but I understand that it doesn't seem to be maintained at the moment. (That and, apparently, building it in the first place required some ugly hacks, not to mention the code's ugly.) I'd offer to help but my plate's pretty full and my Java experience is a bit limited.

**Comment by schildbach** [comment]
Yes, the focus is now on 0.14. That doesn't rule out 0.13.7 however, for example for security fixes.

The only thing being dropped I'm aware of is the generation of the pull-tester.jar. You should be able to start the tool manually though (e.g. through the IDE). My suggestion is to move the tool to the tools subproject, although unfortunately some class dependencies must be untangled for that to happen.

In any case, my understanding is the tool is used for full validation mode only. My perception is full validation needs more love. And perhaps users – are you using it?

**Comment by droark** [comment]
I'm potentially using it. Long story. Day-to-day, I'm not at the moment, but I do think this is a good idea for the project. It's not perfect, and a total refactor might be the best path forward, but I do think thorough testing like this is needed if the project's going to be viable long-term.

As for users, I'd argue that part of the problem is visibility. The only reason I found this was because I was curious about some Core files and config options. Getting info on the feature on my own involved looking at the code and digging up some old dev list posts. (Maybe I missed a resource somehow?) Even now, I'm really not sure how everything came about, why Core added the test option, etc. It would be nice if, at the very least, there was a page that explained everything so that people knew about its existence without digging through source code and such. (I'd be happy to start it. I already have some personal notes.) That would help with the users, IMO. :)
