### ISSUE TITLE
Android tensorflow demo issue :Unable to resolve superclass

### ISSUE THREAD

**Issue by qemb01** [bitcoinj/bitcoinj#1242]
I have built the tensorflow-android-camera-demo by bazel.But the apk does not work.

04-15 09:52:51.039    3225-3225/? D/dalvikvm﹕ Late-enabling CheckJNI
04-15 09:52:51.186    3225-3225/? D/dalvikvm﹕ GC_FOR_ALLOC freed 260K, 10% free 2627K/2912K, paused 8ms, total 8ms
04-15 09:52:51.273    3225-3225/? D/dalvikvm﹕ GC_FOR_ALLOC freed 282K, 10% free 2851K/3164K, paused 9ms, total 9ms
04-15 09:52:51.287    3225-3225/? D/dalvikvm﹕ Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
04-15 09:52:51.531    3225-3225/org.tensorflow.demo D/TextLayoutCache﹕ Using debug level = 0 - Debug Enabled = 0
04-15 09:52:51.591    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Unable to resolve superclass of Lorg/tensorflow/demo/CameraConnectionFragment$2; (33)
04-15 09:52:51.591    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Link of class 'Lorg/tensorflow/demo/CameraConnectionFragment$2;' failed
04-15 09:52:51.592    3225-3225/org.tensorflow.demo D/dalvikvm﹕ DexOpt: unable to opt direct call 0x00cf at 0x0c in Lorg/tensorflow/demo/CameraConnectionFragment;.<init>
04-15 09:52:51.592    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Unable to resolve superclass of Lorg/tensorflow/demo/CameraConnectionFragment$4; (28)
04-15 09:52:51.592    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Link of class 'Lorg/tensorflow/demo/CameraConnectionFragment$4;' failed
04-15 09:52:51.593    3225-3225/org.tensorflow.demo D/dalvikvm﹕ DexOpt: unable to opt direct call 0x00d5 at 0x22 in Lorg/tensorflow/demo/CameraConnectionFragment;.<init>
04-15 09:52:51.594    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Unable to resolve superclass of Lorg/tensorflow/demo/CameraConnectionFragment$5; (29)
04-15 09:52:51.594    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Link of class 'Lorg/tensorflow/demo/CameraConnectionFragment$5;' failed
04-15 09:52:51.594    3225-3225/org.tensorflow.demo D/dalvikvm﹕ DexOpt: unable to opt direct call 0x00d8 at 0xd4 in Lorg/tensorflow/demo/CameraConnectionFragment;.createCameraPreviewSession
04-15 09:52:51.594    3225-3225/org.tensorflow.demo D/dalvikvm﹕ DexOpt: couldn't find static field Landroid/hardware/camera2/CameraCharacteristics;.LENS_FACING
04-15 09:52:51.594    3225-3225/org.tensorflow.demo I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x0004 at 0x1a in Lorg/tensorflow/demo/CameraConnectionFragment;.setUpCameraOutputs
04-15 09:52:51.594    3225-3225/org.tensorflow.demo D/dalvikvm﹕ DexOpt: couldn't find static field Landroid/hardware/camera2/CameraCharacteristics;.SCALER_STREAM_CONFIGURATION_MAP
04-15 09:52:51.594    3225-3225/org.tensorflow.demo I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x0005 at 0x2d in Lorg/tensorflow/demo/CameraConnectionFragment;.setUpCameraOutputs
04-15 09:52:51.598    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Unable to resolve superclass of Lorg/tensorflow/demo/CameraConnectionFragment$2; (33)
04-15 09:52:51.598    3225-3225/org.tensorflow.demo W/dalvikvm﹕ Link of class 'Lorg/tensorflow/demo/CameraConnectionFragment$2;' failed
04-15 09:52:51.599    3225-3225/org.tensorflow.demo D/AndroidRuntime﹕ Shutting down VM
04-15 09:52:51.599    3225-3225/org.tensorflow.demo W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41607568)
04-15 09:52:51.610    3225-3225/org.tensorflow.demo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.tensorflow.demo, PID: 3225
    java.lang.NoClassDefFoundError: org/tensorflow/demo/CameraConnectionFragment$2
            at org.tensorflow.demo.CameraConnectionFragment.<init>(CameraConnectionFragment.java:146)
            at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:269)
            at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.demo.CameraConnectionFragment$2" on path: DexPathList[[zip file "/data/app/org.tensorflow.demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.tensorflow.demo-1, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at org.tensorflow.demo.CameraConnectionFragment.<init>(CameraConnectionFragment.java:146)
            at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:269)
            at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
            at dalvik.system.NativeStart.main(Native Method)
04-15 09:52:51.622    3225-3225/org.tensorflow.demo I/Process﹕ Sending signal. PID: 3225 SIG: 9

Someone solves the issue with eclipse. But I build the apk by bazel, not eclipse.
Help me ...

**Comment by schildbach** [comment]
Looks like you posted to the wrong project.

**Comment by qemb01** [comment]
@schildbach Thanks.
