### ISSUE TITLE
PostgresFullPrunedBlockStore stops [critical]

### ISSUE THREAD

**Issue by yrashk** [bitcoinj/bitcoinj#1246]
I have a case with a full pruning postgres block store when it first fails with a unique constraint (which is rightfully handled by the store), but all the subsequent commands are ignored:  

```
2016-04-20 14:13:08,229 | INFO  | PeerGroup Thread | PeerGroup                        | 58 - bitcoinj - 0.0.0 | 98 blocks/sec, 190 tx/sec, 0 pre-filtered tx/sec, avg/last 56.04/53.55 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
2016-04-20 14:13:09,229 | INFO  | PeerGroup Thread | PeerGroup                        | 58 - bitcoinj - 0.0.0 | 143 blocks/sec, 240 tx/sec, 0 pre-filtered tx/sec, avg/last 55.68/59.57 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
2016-04-20 14:13:10,229 | INFO  | PeerGroup Thread | PeerGroup                        | 58 - bitcoinj - 0.0.0 | 137 blocks/sec, 216 tx/sec, 0 pre-filtered tx/sec, avg/last 57.88/66.16 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
2016-04-20 14:13:11,229 | INFO  | PeerGroup Thread | PeerGroup                        | 58 - bitcoinj - 0.0.0 | 124 blocks/sec, 189 tx/sec, 0 pre-filtered tx/sec, avg/last 63.25/53.72 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
2016-04-20 14:13:12,228 | INFO  | PeerGroup Thread | PeerGroup                        | 58 - bitcoinj - 0.0.0 | 155 blocks/sec, 244 tx/sec, 0 pre-filtered tx/sec, avg/last 57.42/65.90 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
2016-04-20 14:13:12,900 | WARN  | NioClientManager | PeerSocketHandler                | 58 - bitcoinj - 0.0.0 | [76.10.188.111]:8333 -
java.lang.RuntimeException: org.bitcoinj.store.BlockStoreException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:279)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.Peer.processBlock(Peer.java:839)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:358)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180)[58:bitcoinj:0.0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)[58:bitcoinj:0.0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)[58:bitcoinj:0.0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)[58:bitcoinj:0.0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)[68:com.google.guava:19.0.0]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)[68:com.google.guava:19.0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)[58:bitcoinj:0.0.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_25]
Caused by: org.bitcoinj.store.BlockStoreException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.bitcoinj.store.PostgresFullPrunedBlockStore.put(PostgresFullPrunedBlockStore.java:256)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.FullPrunedBlockChain.addToBlockStore(FullPrunedBlockChain.java:113)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:471)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:411)[58:bitcoinj:0.0.0]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:276)[58:bitcoinj:0.0.0]
	... 10 more
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:618)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:468)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:353)
```

I am using bitcoinj 0.13.6, pgsql 9.5.0 and postgresql:9.4-1203-jdbc41 driver.

**Comment by yrashk** [comment]
My current quick-n-dirty solution was to override `addUnspentTransactionOutput` and introduce checkpointing:

```java
 @Override
        public void addUnspentTransactionOutput(UTXO out) throws BlockStoreException {
            try {
                PreparedStatement s = conn.get().prepareStatement("SAVEPOINT insert_utxo");
                s.execute();
            } catch (SQLException e) {
                throw new BlockStoreException(e);
            }
            PreparedStatement s = null;
            try {
                maybeConnect();
                s = conn.get().prepareStatement(getInsertOpenoutputsSQL());
                s.setBytes(1, out.getHash().getBytes());
                // index is actually an unsigned int
                s.setInt(2, (int) out.getIndex());
                s.setInt(3, out.getHeight());
                s.setLong(4, out.getValue().value);
                s.setBytes(5, out.getScript().getProgram());
                s.setString(6, out.getAddress());
                s.setInt(7, out.getScript().getScriptType().ordinal());
                s.setBoolean(8, out.isCoinbase());
                s.executeUpdate();
                s.close();
            } catch (SQLException e) {
                if (e.getSQLState().equals(getDuplicateKeyErrorCode())) {
                    try {
                        PreparedStatement s1 = conn.get().prepareStatement("ROLLBACK TO SAVEPOINT insert_utxo");
                        s1.execute();
                    } catch (SQLException e1) {
                        throw new BlockStoreException(e1);
                    }
                } else {
                    throw new BlockStoreException(e);
                }
            } finally {
                if (s != null) {
                    try {
                        s.close();
                    } catch (SQLException e) {
                        throw new BlockStoreException(e);
                    }
                }
            }
        }
```

Is this something you would consider merging as a PR?

**Comment by yrashk** [comment]
Or we can try INSERT / WHERE NOT EXISTS / RETURNING approach for pgsql. Thoughts?

**Comment by schildbach** [comment]
Pinging @kparmar1 as he is the one who worked on PostgresFullPrunedBlockStore last.

**Comment by kparmar1** [comment]
Sry for the delay... 

This is very strange as this approach is used all over the place with the Postgres/Database stores (i.e an insert error is ignored and an update or something else happens after-- Code must have been hit in the past and have worked?). I know with MySQL this doesn't cause an issue- due to transaction semantics (that's what I've been using).

I didn't write the logic of these classes and I'm not sure why this isn't working now  hmmmm. Yes the solution of check pointing will work fine but there may be other places that this is now required and most of the code is shared between the other stores (so not sure if check pointing may, or may not, make this update difficult).

You cannot use the Where not Exists as is (at the SQL level), as an error is expected and the code does something based on this error- so you would have to rewrite the code in this case. Silent failing of errors (change) will require code updates.

I'm at a lose to explain why we are seeing this now, unless this never happened before of course (so the code was never hit). I'll take a look and see if I can figure out what's going on.

**Comment by kparmar1** [comment]
Actually maybe in the case you can (the WHERE EXISTS -- but if it's happening here it should happen elsewhere as well)

**Comment by kparmar1** [comment]
I'm a little bit snowed under at the moment (work and life stuff eeek). If the solution works maybe go with it. I'll try and find some time but it looks like yrashk has it covered. Kal.
