### ISSUE TITLE
VerificationException on Testnet - wallet stops adding new blocks to height - SPVBlockStore ring overflow

### ISSUE THREAD

**Issue by jarlfr** [bitcoinj/bitcoinj#1257]
On testnet sometimes a bitcoinj wallet stops adding blacks to height and never recover unless a full chain download is made. I made some early analysis of one reason this can happen.

In brief, my early analysis is this:

* On testnet there have been some very heavy burst of blocks received in my case. In particular this occured on May 7, 2016.
* When running with SPVBlockStore, the internal ring buffer of 5000 blocks kept for validation seems to "overflow" in the sense that it has less than the required 2016 blocks from the chain head to its oldest block. This is needed for difficulty check, when a difficulty change occurs.
* It results in VerificationException with message "Difficulty transition point but we did not find a way back to the genesis block", and the store will never add more blocks to head.

The VerificationException looks like this:

> 2016-05-07 21:00:09,721 WARN  [NioClientManager] org.bitcoinj.core.Peer - [79.98.25.77]:18333: FilteredBlock verification failed
org.bitcoinj.core.VerificationException: Could not verify block 00000000000235e5e33a21e29d2750b3ea504da717770b21512c1c4a9414355e
FilteredBlock{merkleTree=PartialMerkleTree{transactionCount=1, matchedChildBits=[0], hashes=[bbca1cf79ee349e9c6d85d405a782cdafacde13c7db2a1e502614294db3832b1]}, header= block: 
   hash: 00000000000235e5e33a21e29d2750b3ea504da717770b21512c1c4a9414355e
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 00000000000bfec54977673f68b6fe5f088398e697d778fa7987f8bab6a70825
   merkle root: bbca1cf79ee349e9c6d85d405a782cdafacde13c7db2a1e502614294db3832b1
   time: 1462625889 (2016-05-07T12:58:09Z)
   difficulty target (nBits): 453309060
   nonce: 2765832993
}
   at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:392)
        at org.bitcoinj.core.BlockChain.add(BlockChain.java:166)
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1081)
      at org.bitcoinj.core.Peer.processMessage(Peer.java:460)
 at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
 at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
     at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
     at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
     at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
 at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.bitcoinj.core.VerificationException: Difficulty transition point but we did not find a way back to the genesis block.
    at org.bitcoinj.params.AbstractBitcoinNetParams.checkDifficultyTransitions(AbstractBitcoinNetParams.java:87)
    at org.bitcoinj.params.TestNet3Params.checkDifficultyTransitions(TestNet3Params.java:117)
       at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:488)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:381)
        ... 11 common frames omitted

What to do?

As this happens for _testnet_ and with _SPVBlockStore_ and a fresh block download can be used to work around it, maybe this is not very urgent to fix. 

However, we could make explicit an invariant in BlockStores that we always must keep enough blocks to perform the `checkDifficultyTransitions` else the Store would fail this check.

**Comment by schildbach** [comment]
Thanks for analyzing this, it's much appreciated!

Yes, I think the problem is that the ring buffer does not "roll back" on re-orgs. So if you have a 2 block re-org, the orphaned 2 blocks stay in the ring with the blocks from the best chain appended. If someone runs a race between 2 chains with both chains getting the lead in an alternating way the 5000 entries in the ring buffer will be filled up quickly, without the ability to seek back to the last difficulty transition point.

I see these possibilities:

1. Simply abandon Testnet. Mike has suggested this many times. I always objected because I think Testnet is valuable. Even if these frequent reorgs are a hassle, at least they test the reorg logic quite thoroughly. Those code paths are almost never run on Mainnet.
2. Increase the ring buffer size. Mobile phones have a lot more storage these days, so I think doubling would not be a problem. Do you have statistics on how much would be needed? Do you perhaps would like to run some tests? The size is in `DEFAULT_NUM_HEADERS`; we might increase the two cache sizes as well (lines 62 and 75).
3. Make sure reorged blocks are properly rolled back in the store. I'm not sure if this is easily possible.

> However, we could make explicit an invariant in BlockStores that we always must keep enough blocks to perform the checkDifficultyTransitions else the Store would fail this check.

Would this change anything? If this invariant fails, the store is in an unusable state anyway and requires a replay. But if it's easy to implement I'm all for it as it would improve debug/exception traces.

**Comment by jarlfr** [comment]
I agree that there are many benefits to keeping testnet alive, for the reasons you mention.  

Increasing the buffer would be a quick fix solution but the question is how much would be enough then.

The idea with the invariant was just to state the design assumptions more clearly when it comes to BlockStores.  But, thinking along those lines, would it be possible to make a BlockStore reject further put operations when it detect it is "full"?  Thus the chain head has to be "moved" forward a certain amount before more can be put in.  The rejected blocks have to be requested again from the network peers somehow. Could this even work? It would shift some responsibility ouside the BlockStore. Sorry, but I am not expert on the bitcoinj code or what the protocol with peers would let us do.  

It is not a solution, and not very general, but I noticed you can catch this particular exeption in a derived class of `TestNet3Param` with and overridden `checkDifficultyTransitions`. Maybe this is not so dangerous as long as we are sure we run on testnet.

**Comment by schildbach** [comment]
I'm seeing this on mainnet as well, but perhaps due to different reasons. See attached log. What happens is that the app is crashing (or killed by the user) while happily downloading blocks at high speed. This usually results in a height inconsistency between the block store and the wallet, so the blockstore is rolled back to the height of the wallet on next restart. In this case, because of the high speed, the block store was rolled back by a whopping 4792 blocks – so almost the entire 5000 blocks! No wonder it cannot find a way back to the last transition point (btw. the exception message is wrong).

As a quick workaround, I will save the wallet more often. Mid-term I propose to [double the capacity](https://github.com/bitcoinj/bitcoinj/pull/1293) of the ring buffer. I think modern devices can take that easily these days. Long-term we could work on atomic wallet+blockstore updates.

[wallet.670555865.log.txt](https://github.com/bitcoinj/bitcoinj/files/442114/wallet.670555865.log.txt)

**Comment by jarlfr** [comment]
Yes, I agree that if that amount of blocks are rolled back the SPVBlockStore is likely to stop working as it was designed.

Just a few comments about doubling capacity. I did a quick variant (you can have it) of the store with an constructor argument instead of DEFAULT_NUM_HEADERS to try different sizes. For a production ready store, there has to be a robust "upgrade" from lower/different number of blocks in the file that the code, or a different HEADER_MAGIC to detect that wallet files are not compatible upgrade. Maybe the HEADER_MAGIC field of the file could be used to signal the size of the file? This is nothing very hard but just to take into account.

This is just an idea: is it a working strategy in this case, as you describe the problem on the main net, and considering the current code, to somehow limit the number of blocks in the store accepted that is ahead of the wallet? Maybe limit to max 1000 blocks more in the store than the wallet, by some way, maybe even disconnect the peers and connect later after wallet catches up.  This would maybe limit fast download but it could be a safe solution?  I do not really understand the downloading model in detail and how the threads etc. but in general to be simple and safe a good way is to rely on the network nodes.  This particular case seems to happen seldom but when it does its bad for the user so it is ok if it takes a bit of time and effort for nodes.

**Comment by schildbach** [comment]
If you look at the constructor it compares the filesize to how big it expects the file to be. It will throw an exception if its not the right size.

Yes I agree we need some migration code for production. But for now we can just play around with it. (Currently Bitcoin Walllet will migrate the blockstore by replaying the chain…)

I don't really want to throttle blockchain replay. It takes too long already…

**Comment by schildbach** [comment]
Just examined another variant of this. User installed the wallet, blockstore initialized to the checkpointed block 459648, bitcoin quickly synched 6000 blocks but then the app crashed without the wallet being saved for the last 4000 blocks. Upon app restart, the height mismatch was detected and 4000 blocks on the block store rolled back. Since the block store has only a capacity of 5000, there is now no transition point in the store, leading to a verification exeption at the next incoming difficulty transition point.

We could try to prevent rollbacks that don't leave a transition point in the blockstore. With the proper exception handling, it would then have lead to a reset of the wallet and clean replay. However, I still think it's time for doubling the size of the block store.

[wallet.1596677245.log.txt](https://github.com/bitcoinj/bitcoinj/files/1109462/wallet.1596677245.log.txt)
