### ISSUE TITLE
AccessControlException in WindowsMMapHack

### ISSUE THREAD

**Issue by ScripterRon** [bitcoinj/bitcoinj#1297]
I'm getting an unhandled exception when stopping the wallet.  The custom security policy does not allow loading from sun.nio.ch.  This will be a problem in Java 9 even with the default security manager.

2016-09-08 11:02:56 INFO: BitcoinWallet.shutdown: Waiting for Bitcoin wallet to stop ...
Exception in thread " STOPPING" Exception in thread "Thread-0" java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.ch")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPackageAccess(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.bitcoinj.store.WindowsMMapHack.forceRelease(WindowsMMapHack.java:36)
        at org.bitcoinj.store.SPVBlockStore.close(SPVBlockStore.java:267)
        at org.bitcoinj.kits.WalletAppKit.shutDown(WalletAppKit.java:489)
        at com.google.common.util.concurrent.AbstractIdleService$2$2.run(AbstractIdleService.java:69)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Unknown Source)

**Comment by schildbach** [comment]
What OS do you use?

**Comment by ScripterRon** [comment]
I use Windows 10.  My temporary circumvention is to just catch the exception and ignore it since my application only closes the block store during application termination, so it doesn't matter if the mapped pages are released.  Note that this is currently only a problem with a custom Java security manager since the default security manager allows the class to be loaded.  My understanding is this will be a problem with Java 9 though.

**Comment by schildbach** [comment]
It would be interesting to know if newer Java versions still have the bug this class is working around.

**Comment by ScripterRon** [comment]
I don't know enough about the internal workings to tell.  I couldn't find anything saying that the behavior had changed.  We could catch the exception for now and then see what happens when Java 9 is released next year.

**Comment by msgilligan** [comment]
@schildbach Can we close this issue? It's 3.5 years old and likely fixed.

**Comment by schildbach** [comment]
Indeed, thanks.
