### ISSUE TITLE
Postgres blockchain issue

### ISSUE THREAD

**Issue by Dragomirus** [bitcoinj/bitcoinj#1311]
I've found serious issue in bitcoinj. Postgres blockchain works good on testnet but if you want to download blockchain on mainnet there is no way to achieve this. Everything is ok before block number 91841. After this block this message always appear:

`java.lang.RuntimeException: org.bitcoinj.store.BlockStoreException: org.postgresql.util.PSQLException: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:355)
	at org.bitcoinj.core.Peer.processBlock(Peer.java:987)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:491)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bitcoinj.store.BlockStoreException: org.postgresql.util.PSQLException: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
	at org.bitcoinj.store.PostgresFullPrunedBlockStore.put(PostgresFullPrunedBlockStore.java:257)
	at org.bitcoinj.core.FullPrunedBlockChain.addToBlockStore(FullPrunedBlockChain.java:113)
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:562)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:489)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:352)
	... 10 more
Caused by: org.postgresql.util.PSQLException: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
	at org.bitcoinj.store.PostgresFullPrunedBlockStore.put(PostgresFullPrunedBlockStore.java:205)
	... 14 more

What I should do?

**Comment by schildbach** [comment]
This is not a support forum. Please post to the bitcoinj mailing list. Also, can you switch your computer to English before producing the exception trace?

**Comment by Dragomirus** [comment]
But it's not a problem on my side. This issue always appear on every single computer when I'm start downloading blockchain. Sorry I will correct my first message :)

**Comment by Dragomirus** [comment]
Ok, I fixed it. All informations are in this thread: https://github.com/bitcoinj/bitcoinj/issues/1246. Hope you will add this to head soon.
