### ISSUE TITLE
IllegalArgumentException when calling isSentToMultiSig

### ISSUE THREAD

**Issue by alecalve** [bitcoinj/bitcoinj#1328]
Trying to decode the output script of [this transaction](https://blockchain.info/tx/514c46f0b61714092f15c8dfcb576c9f79b3f959989b98de3944b19d98832b58) with :
```java
String hex = "210378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c717c8bae";
Script script = new Script(Hex.decode(hex));
script.isSentToMultiSig();
```

results in the following exception:

```
java.lang.IllegalArgumentException: decodeFromOpN called on non OP_N opcode

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.bitcoinj.script.Script.decodeFromOpN(Script.java:577)
	at org.bitcoinj.script.Script.isSentToMultiSig(Script.java:707)
```

**Comment by natzei** [comment]
The script is not a check-multisig. However, `isSentToMultiSig` was handling the wrong exception. #1413 should fix it.

**Comment by schildbach** [comment]
#1413 was merged.
