### ISSUE TITLE
bitcoinj fails to deserialize the new 0.13+ block format from bitcoind

### ISSUE THREAD

**Issue by rktoomey** [bitcoinj/bitcoinj#1336]
# Summary

bitcoinj running peered against 0.13+ nodes does just fine - it signals that it can't handle the new block format and everything is OK.  But if you are using bitcoind JSON-RPC and deserializing hex, you will have an issue until:

1. you upgrade your 0.13+ nodes to 0.13.2 and use `rpcserialversion=0`, or
2. bitcoinj updates the message serializer to handle the new block format

# Details

Using bitcoind JSON-RPC on a new 0.13.2 testnet3 node, I encountered a failure using bitcoinj 0.14.3 to deserialize this block:

```json
{
  "method" : "getblock",
  "params" : [ "0000000000332ef392f66e80afa2bb1389c08f47050ea189ae432e7bfea8c36e", false ],
  "id" : "segwit-up-in-my-grill"
}
```

The hex returned in the result fails to deserialize using as expected:

```java
networkParams.getDefaultSerializer.makeBlock(hex)
```

because

```java
[info]   Cause: org.bitcoinj.core.ProtocolException: Claimed value length too large: 50331647
[info]   at org.bitcoinj.core.Message.readBytes(Message.java:331)
[info]   at org.bitcoinj.core.TransactionOutput.parse(TransactionOutput.java:163)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:96)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:128)
[info]   at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
[info]   at org.bitcoinj.core.TransactionOutput.<init>(TransactionOutput.java:79)
[info]   at org.bitcoinj.core.Transaction.parse(Transaction.java:568)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:96)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:128)
[info]   at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
[info]   at org.bitcoinj.core.Transaction.<init>(Transaction.java:227)
[info]   at org.bitcoinj.core.Block.parseTransactions(Block.java:242)
[info]   at org.bitcoinj.core.Block.parse(Block.java:266)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:96)
[info]   at org.bitcoinj.core.Message.<init>(Message.java:128)
[info]   at org.bitcoinj.core.Block.<init>(Block.java:162)
[info]   at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
[info]   at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:72)
```

## What changed

To document this for the next person to encounter this error 😸 , if you're using JSON-RPC with a bitcoind 0.13+ node then by default the block format has changed:
https://www.reddit.com/r/Bitcoin/comments/5dx86y/psa_segwit_changes_the_format_of_data_returned_by/

Attached are the old and new block formats in hex for `0000000000332ef392f66e80afa2bb1389c08f47050ea189ae432e7bfea8c36e`.  

Note that the new format is 70 characters longer than the old format.  

Old format taken from an 0.10 node; new format taken from an 0.13.2 node _before_ flipping the `rpcserialversion` flag to `0`.  (After flipping that flag and restarting, the two nodes return identical hex).

[old_format.txt.zip](https://github.com/bitcoinj/bitcoinj/files/750799/old_format.txt.zip)
[new_format.txt.zip](https://github.com/bitcoinj/bitcoinj/files/750834/new_format.txt.zip)

## How to fix your nodes

Not well publicised, but there is a `-rpcserialversion` flag released with 0.13.2 which fixes the immediate problem by reverting to the previous block format when you use `rpcserialversion=0`:
https://github.com/bitcoin/bitcoin/pull/9194

cc @schildbach thanks for your help

**Comment by rktoomey** [comment]
Haven't tested whether this is fixed by #1334

**Comment by TheBlueMatt** [comment]
I suppose this is expected behavior (and is why the -rpcserialversion was added). Without SegWit activating on mainnet soon there is little reason to merge it into bitcoinj, hence bitcoinj simply doesnt support testnet3 in full validation mode.

**Comment by rktoomey** [comment]
Thanks, I figured as much, I just wanted to record it for the next person as well as helping to make sure the segwit branch will correctly deserialize this block.

**Comment by schildbach** [comment]
Ok, I'll close this for now.

**Comment by devinrsmith** [comment]
Just ran into this issue and spent a while debugging it (on latest release, 0.14.5). I added `rpcserialversion=0` and that fixed the issue, so it's easy enough to work around. If bitcoinj isn't planning to add support for the new format, it might be nice for bitcoinj to realize it is parsing the new format, and throw a more relevant error message, something like "New rpc serial format not supported, see https://github.com/bitcoinj/bitcoinj/issues/1336".

**Comment by schildbach** [comment]
I'm happy to accept a PR for either of the two options. Since you have a test environment running, would you like to take a stab at the warning message?

**Comment by scalahub** [comment]
I encountered this while parsing blk00975.dat. The error was: 
`org.bitcoinj.core.ProtocolException:` Claimed value length too large: 1076182423`

Using the version 0.14.5 of Bitcoinj
