### ISSUE TITLE
BIP130 - sendheaders not supported?

### ISSUE THREAD

**Issue by globaltoken** [bitcoinj/bitcoinj#1423]
Hey,

If I run the Code I got this Exception:

> 20:58:27 [NioClientManager] BitcoinSerializer - No support for deserializing message with name sendheaders
20:58:27 [NioClientManager] PeerSocketHandler  - 
org.bitcoinj.core.ProtocolException: Error deserializing message 

	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:185) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:146) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:153) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:530) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:100) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:124) ~[na:0.0]
	at org.bitcoinj.core.EmptyMessage.<init>(EmptyMessage.java:41) ~[na:0.0]
	at org.bitcoinj.core.UnknownMessage.<init>(UnknownMessage.java:28) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:234) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:183) ~[na:0.0]
	... 9 common frames omitted
20:58:27 [NioClientManager] WalletApplication - bitcoinj uncaught exception
org.bitcoinj.core.ProtocolException: Error deserializing message 

	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:185) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:146) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:153) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:530) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:100) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:124) ~[na:0.0]
	at org.bitcoinj.core.EmptyMessage.<init>(EmptyMessage.java:41) ~[na:0.0]
	at org.bitcoinj.core.UnknownMessage.<init>(UnknownMessage.java:28) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:234) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:183) ~[na:0.0]
	... 9 common frames omitted

Whats wrong ?

**Comment by schildbach** [comment]
Yes, I guess there wasn't any use for it so far.

**Comment by globaltoken** [comment]
Okay, another Error that caused:

23:13:37 13 Secp256k1Context.<clinit>: java.lang.UnsatisfiedLinkError: no secp25
6k1 in java.library.path

Where can I get this Lib?

**Comment by schildbach** [comment]
This is not a support forum. Please post to the mailing list.
