### ISSUE TITLE
Blockchain download fails 

### ISSUE THREAD

**Issue by abubakerkhidir** [bitcoinj/bitcoinj#1450]
hi 

I am new to bitcoinj and trying to use it for a wallet app. I am having a problem starting bitcoinj wallet on testnet3, at first it was working ok and i was able to send and receive couple of transactions without issues, then suddenly it started to hang every time I start it. It work when I delete the blockstore file, but when I put it back (or restart after a successfull run) it hangs again. I check the log and it seems all the peers are dying due to the below exceptions:

[32m01:06:17.269 INFO  [NioClientManager] (:) - [136.243.88.194]:18333: Peer died      (0 connected, 12 pending, 12 max)[m
[32m01:06:17.270 INFO  [NioClientManager] (:) - Download peer died. Picking a new one.[m
[32m01:06:17.270 INFO  [NioClientManager] (:) - Unsetting download peer: [136.243.88.194]:18333[m
[33m01:06:17.270 WARN  [NioClientManager] (:) - Error handling SelectionKey: java.lang.IllegalStateException [m
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158) ~[guava-18.0.jar:?]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:224) [bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.14.4.jar:?]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-18.0.jar:?]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [guava-18.0.jar:?]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [bitcoinj-core-0.14.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

and 

[33m01:06:18.314 WARN  [NioClientManager] (:) - [86.247.86.131]:18333 - [m
java.lang.NullPointerException: null
	at org.bitcoinj.params.TestNet3Params.checkDifficultyTransitions(TestNet3Params.java:107) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:488) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:381) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:166) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1093) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:470) ~[bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182) [bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.14.4.jar:?]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.14.4.jar:?]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-18.0.jar:?]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [guava-18.0.jar:?]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [bitcoinj-core-0.14.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[32m01:06:18.315 INFO  [NioClientManager] (:) - [86.247.86.131]:18333: Peer died      (8 connected, 1 pending, 12 max)[m
[32m01:06:18.315 INFO  [NioClientManager] (:) - Download peer died. Picking a new one.[m
[32m01:06:18.315 INFO  [NioClientManager] (:) - Unsetting download peer: [86.247.86.131]:18333[m

below is a test class replicating the issue. (I have attached the bitcoin.wallet and bitcoin.spvchain, zipped under test3 directory)

[app-log.txt](https://github.com/bitcoinj/bitcoinj/files/1308697/app-log.txt)
[test3.zip](https://github.com/bitcoinj/bitcoinj/files/1308699/test3.zip)

`public class BitcoinTest extends WalletAppKit{
	private static final Logger logger = LogManager.getLogger();
	private BitcoinTest manager;
	
	
	public BitcoinTest(NetworkParameters params, File directory, String filePrefix) {
		super(params, directory, filePrefix);
	}

	public void startWallet() {
		logger.info("Starting Bitcoin Wallet...");
		manager = this;
		this.autoStop = false;
		this.blockingStartup = false;
		this.downloadListener = new DownloadMonitor();
        startAsync();
        Runtime.getRuntime().addShutdownHook(new Thread() {
        	@Override
        	public void run() {
        		manager.stopAsync();
        	}
        });
        awaitRunning();
	}
	
	
	private class DownloadMonitor extends DownloadProgressTracker {
		
		public DownloadMonitor() {
			super();
		}

		protected void progress(double pct, int blocksSoFar, Date date) {
			logger.info(String.format(Locale.US, "Chain download %d%%, remaining blocks %d, block date %s", (int) pct, blocksSoFar,
		            Utils.dateTimeFormat(date)));
		}

		@Override
		protected void doneDownload() {
			logger.info("Full Bitcoin blockchain is downloaded... ");
		}

		@Override
		public void onChainDownloadStarted(Peer peer, int blocksLeft) {
			super.onChainDownloadStarted(peer, blocksLeft);
			logger.info("blockchain download started ... blocksLeft [{}], myBestBlock [{}], peerBestBlock [{}], peer [{}], peerCount[{}]"
			   ,blocksLeft,chain().getBestChainHeight(), peer.getBestHeight(),peer.getAddress(),manager.peerGroup().numConnectedPeers());
		}
	}
	
	public static void main(String[] args) {
		BitcoinTest b = new BitcoinTest(TestNet3Params.get(), new File("test3"), "bitcoin");
		b.startWallet();
		while(true) {
			
		}
	}
}
`

**Comment by atlas-shrugging** [comment]
Did you ever figure out what happened? I am getting this same issue.

**Comment by ander7agar** [comment]
I have this same problem. @abubakerkhidir or @gcbrown,  you managed to solve it?

**Comment by gcbrown** [comment]
I found it was a problem with the hardfork in November. So I only made my header file up to October and download October through present. It's not the best solution but it's the best I could come up with.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
