### ISSUE TITLE
Running ForwardingService with "testnet" giving error

### ISSUE THREAD

**Issue by vineettyagi28** [bitcoinj/bitcoinj#1467]
`Exception in thread "main" java.lang.NoClassDefFoundError: org/spongycastle/asn1/ASN1Encodable
	at org.bitcoinj.core.Block.<clinit>(Block.java:896)
	at org.bitcoinj.core.NetworkParameters.createGenesis(NetworkParameters.java:116)
	at org.bitcoinj.core.NetworkParameters.<init>(NetworkParameters.java:112)
	at org.bitcoinj.params.AbstractBitcoinNetParams.<init>(AbstractBitcoinNetParams.java:52)
	at org.bitcoinj.params.MainNetParams.<init>(MainNetParams.java:36)
	at org.bitcoinj.params.MainNetParams.get(MainNetParams.java:138)
	at com.scopeweaver.scopebit.ForwardingService.main(ForwardingService.java:71)
Caused by: java.lang.ClassNotFoundException: org.spongycastle.asn1.ASN1Encodable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
`
When trying to run ForwardingService from examples, above mentioned error is coming.

**Comment by vineettyagi28** [comment]
If anyone else is having the same issue, you will have to include updated spongycastle dependency in your pom.xml

             `</dependency>
			<dependency>
			<groupId>com.madgag.spongycastle</groupId>
			<artifactId>core</artifactId>
			<version>1.58.0.0</version>
		</dependency>`

Spongy castle project has been completely updated which broke many projects depend on it.
