### ISSUE TITLE
Running getting started leads to org.bitcoinj.core.ScriptException: Attempted OP_DUP on an empty stack

### ISSUE THREAD

**Issue by eepstein** [bitcoinj/bitcoinj#1561]
log with partial Stack trace:

```
00:35:08.330 [bitcoinj user thread] INFO com.tokenopoly.coinbridge.WalletAppKitTest - Forwarding 0.65 BTC BTC
00:35:08.351 [NioClientManager] INFO org.bitcoinj.wallet.WalletFiles - Save completed in 34.04 ms
00:35:08.352 [bitcoinj user thread] INFO org.bitcoinj.wallet.Wallet - Completing send tx with 1 outputs totalling 0.649 BTC and a fee of 0.001 BTC/kB
00:35:08.369 [bitcoinj user thread] INFO org.bitcoinj.wallet.Wallet -   with 0.000773 BTC change
00:35:08.374 [bitcoinj user thread] DEBUG org.bitcoinj.wallet.Wallet - Input contained an incorrect signature
org.bitcoinj.core.ScriptException: Attempted OP_DUP on an empty stack
	at org.bitcoinj.script.Script.executeScript(Script.java:1058)
	at org.bitcoinj.script.Script.correctlySpends(Script.java:1600)
	at org.bitcoinj.script.Script.correctlySpends(Script.java:1570)
	at org.bitcoinj.wallet.Wallet.signTransaction(Wallet.java:4052)
	at org.bitcoinj.wallet.Wallet.completeTx(Wallet.java:3998)
	at org.bitcoinj.wallet.Wallet.sendCoinsOffline(Wallet.java:3762)
	at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:3829)
	at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:3798)
	at example.WalletAppKitTest.forwardCoins(WalletAppKitTest.java:134)
```

Relevant code:

    private static void forwardCoins(Transaction tx) {

        Coin value = tx.getValueSentToMe(kit.wallet());
        log.info("Forwarding {} BTC", value.toFriendlyString());
// Now send the coins back! Send with a small fee attached to ensure rapid confirmation.
        final Coin amountToSend = value.subtract(Transaction.DEFAULT_TX_FEE);

        try {
            // Now send the coins onwards.
//            SendRequest sendRequest = SendRequest.emptyWallet(forwardingAddress);
//            Wallet.SendResult sendResult = kit.wallet().sendCoins(sendRequest);

            // This next line is line 134 and results in the exception.
            final Wallet.SendResult sendResult = kit.wallet().sendCoins(kit.peerGroup(), forwardingAddress, amountToSend);

            checkNotNull(sendResult);  // We should never try to send more coins than we have!
            log.info("Sending ...");
            // Register a callback that is invoked when the transaction has propagated across the network.
            // This shows a second style of registering ListenableFuture callbacks, it works when you don't
            // need access to the object the future returns.
            sendResult.broadcastComplete.addListener(() -> {
                // The wallet has changed now, it'll get auto saved shortly or when the app shuts down.
                log.info("Sent coins onwards! Transaction hash is {}", sendResult.tx.getHashAsString());
            }, MoreExecutors.directExecutor());
        } catch (KeyCrypterException | InsufficientMoneyException e) {
            // We don't use encrypted wallets in this example - can never happen.
            log.error("Unable to forward funds", e);
        }
    }

**Comment by GySir** [comment]
Did you solve it

**Comment by eepstein** [comment]
Yes.  I changed the code to the other version they had - the examples were inconsistent, the code in the explainer was different than the code in the single source file.  After changing it to the less clear code this went away.

**Comment by GySir** [comment]
Thank you for your reply,but i am puzzled with what you say. This problem will not appear if the code has " kit.connectToLocalHost()", but if it connects other network nodes ,this problem appears. could you give me some detail information such as your code or the version of bitcoinj...... please

**Comment by schildbach** [comment]
Can you always say on what branch, tag or commit of bitcoinj you're working on?
