### ISSUE TITLE
BtcFormat.format(String) Fails To Produce Expected Negative Format

### ISSUE THREAD

**Issue by limey-git** [bitcoinj/bitcoinj#1657]
openjdk version "12-ea" 2019-03-19
    OpenJDK Runtime Environment (build 12-ea+15)
    OpenJDK 64-Bit Server VM (build 12-ea+15, mixed mode, sharing)
    --------
    limey@git:~/bitcoinj.wallet$ uname -a
    Linux limey 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 08:19:09 PST 2018 x86_64 x86_64 x86_64            GNU/Linux

    -------

According to the javadoc for `BtcFormat.Builder.pattern(String)`, it's expected to behave like `java.util.DecimalFormat`. Except, it doesn't:

    jshell> new DecimalFormat("฿#,##0.00;(฿#)").format(Integer.MIN_VALUE);
    $26 ==> "(฿2,147,483,648.00)"

    jshell> BtcFormat.builder().pattern("฿#,##0.00;(฿#)").build().format(Integer.MIN_VALUE);  
    $27 ==> "(฿21.47)"

If you don't explicitly provide a custom pattern on the builder, and use the default one, negative values are prefixed with the negative symbol (`-`) instead of being wrapped in parenthesis.

I have observed several failing tests in `BtcFormatTest`, like this one, that are caused by this defect:

     ...
    org.junit.ComparisonFailure: expected:<[(µ฿21,474,836.48)]> but was:<[µ฿-21,474,836.48]>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at org.bitcoinj.utils.BtcFormatTest.argumentTypeTest(BtcFormatTest.java:159)
            ...

Please advise how to make `BtcFormat.format(String)` correctly format the output using the caller-provided negative pattern?

**Comment by limey-git** [comment]
I forgot to tell you: I'm getting this from code I cloned from the master branch/[commit ad262de9619fa4c86c34bece7288ef1e18335b06](https://github.com/bitcoinj/bitcoinj/commit/ad262de9619fa4c86c34bece7288ef1e18335b06).

**Comment by limey-git** [comment]
Apologies. I was able to successfully build using jdk 8:

----
    java version "1.8.0_191"
    Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
----

**Comment by limey-git** [comment]
Actually, although the project does successfully build with JDK8  (*all the tests PASS*), the `BtcFormat.Builder.pattern(String)` defect I described above, is still not resolved:

----
    jshell> new DecimalFormat("฿#,##0.00;(฿#)").format(Integer.MIN_VALUE);
    $26 ==> "(฿2,147,483,648.00)"


    jshell> BtcFormat.builder().pattern("฿#,##0.00;(฿#)").build().format(Integer.MIN_VALUE);  
    $27 ==> "(฿21.47)"
----

Please advise how to make the above snippet produce the correct result for negative Integers?

**Comment by schildbach** [comment]
@mackler Do you have an idea on this?

@limey-git Are you aware of `MonetaryFormat`?

**Comment by limey-git** [comment]
Thanks @schildbach,

I couldn't figure out a straightforward way to make `MonetaryFormat` return the exact format I need: ("*(฿2,147,483,648.00)*") 

However, [*I did eventually figure out*](https://github.com/bitcoinj/bitcoinj/files/2511919/BtcFormatTest.java.0.txt) that I could get the precise expected value, and scale, printed in the exact negative format I need, by passing a `java.math.BigDecimal` to `BtcFormat.format(Object)`.

Even so, [*the `BtcFormat.Builder.pattern(String)` javadoc*](https://bitcoinj.github.io/javadoc/0.14.7/org/bitcoinj/utils/BtcFormat.Builder.html#pattern-java.lang.String-) says:

----
> "...*The format of this pattern is identical to that used by the [DecimalFormat](http://docs.oracle.com/javase/6/docs/api/java/text/DecimalFormat.html?is-external=true) class*..."
----
Reading that, It seems like if I give it the exact same pattern string that I give `DecimalFormat.format()`, that I should expect to get the exact same result. No?

**Comment by mackler** [comment]
It's been so long since I've looked at this my memory of it is quite dim. If I can find time to look at it I will.  I apologize for lacking a more satisfying response.

**Comment by lucash-dev** [comment]
I've had the same issue when building with OpenJDK. It seems underlying NumberFormat behaviour isn't very well defined.
