### ISSUE TITLE
java.lang.NoSuchMethodError: Stopwatch.createStarted()

### ISSUE THREAD

**Issue by stasbar** [bitcoinj/bitcoinj#1659]
Hello,
I'm getting
```
java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.createStarted()Lcom/google/common/base/Stopwatch;
	at org.bitcoinj.crypto.MnemonicCode.toSeed(MnemonicCode.java:135)
	at org.bitcoinj.wallet.DeterministicSeed.<init>(DeterministicSeed.java:81)
```
from here
```java
    public static byte[] toSeed(List<String> words, String passphrase) {
        checkNotNull(passphrase, "A null passphrase is not allowed.");
        String pass = Utils.join(words);
        String salt = "mnemonic" + passphrase;

        final Stopwatch watch = Stopwatch.createStarted(); // <-- from here
        byte[] seed = PBKDF2SHA512.derive(pass, salt, PBKDF2_ROUNDS, 64);
        watch.stop();
        log.info("PBKDF2 took {}", watch);
        return seed;
    }
```
when using with JUnit
here is my test
```java
    @Test
    void initWalletFromSeed() throws BlockStoreException, UnknownHostException {
        NetworkParameters params = TestNet3Params.get();
        List<String> mnemonicCode = Arrays.asList(
                "mnemonic code".split(" "));
 // throws here 
        DeterministicSeed seed = new DeterministicSeed(mnemonicCode, null, "", 1539388800);
        Wallet wallet = Wallet.fromSeed(params, seed);
        final SPVBlockStore blockStore = new SPVBlockStore(params, blockstoreFile);
        BlockChain chain = new BlockChain(params, wallet, blockStore);

        PeerGroup peerGroup = new PeerGroup(params,chain);
        peerGroup.setUserAgent("RaspberryWallet", "1.0");
        peerGroup.addPeerDiscovery(new DnsDiscovery(params));
        peerGroup.addAddress(new PeerAddress(params, InetAddress.getLocalHost()));
        peerGroup.startAsync();
        peerGroup.downloadBlockChain();
        peerGroup.stopAsync();

        // And take them!
        System.out.println("Wallet balance" + wallet.getBalance().toFriendlyString());
    }
```
my pom.xml
```xml
        <dependency>
            <groupId>org.bitcoinj</groupId>
            <artifactId>bitcoinj-core</artifactId>
            <version>0.14.7</version>
            <scope>compile</scope>
        </dependency>
```

It works fine when I'm using it from production code.

**Comment by schildbach** [comment]
You likely have no Guava or maybe a very old version of it on the classpath.

Please ask questions on the mailing list. Thanks.

**Comment by acuna-public** [comment]
Yes, I have no Guava, but why I need to have it only to get execution time in logs?
