### ISSUE TITLE
Exception in thread "NioClientManager" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by thotheolh** [bitcoinj/bitcoinj#1666]
I am getting OutOfMemory Exception when downloading the blockchain causing the entire application to crash.

I am using BitcoinJ Core 0.14.7 when getting the error.

Exception in thread "NioClientManager" java.lang.OutOfMemoryError: Java heap space
    at org.bitcoinj.core.Utils.copyOf(Utils.java:430)
    at org.bitcoinj.core.UnsafeByteArrayOutputStream.toByteArray(UnsafeByteArrayOutputStream.java:118)
    at org.bitcoinj.core.Message.unsafeBitcoinSerialize(Message.java:245)
    at org.bitcoinj.core.Transaction.getHash(Transaction.java:254)
    at org.bitcoinj.core.Transaction.getConfidence(Transaction.java:1188)
    at org.bitcoinj.core.Transaction.getConfidence(Transaction.java:1180)
    at org.bitcoinj.core.Transaction.getConfidence(Transaction.java:1172)
    at org.bitcoinj.core.Block.parseTransactions(Block.java:244)
    at org.bitcoinj.core.Block.parse(Block.java:266)
    at org.bitcoinj.core.Message.<init>(Message.java:96)
    at org.bitcoinj.core.Message.<init>(Message.java:128)
    at org.bitcoinj.core.Block.<init>(Block.java:162)
    at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
    at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:80)
    at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:197)
    at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:183)
    at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:144)
    at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
    at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
    at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
    at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by thotheolh** [comment]
JVM is given this parameter -Xmx2048m (2048 MB memory) to work with.

**Comment by schildbach** [comment]
That means you're running out of heap space.

**Comment by thotheolh** [comment]
I have already allocated 2048 MB of RAM and it still seems not to satisfy the BitcoinJ. How much memory do I need to allocate to it to allow it to operate without running out of memory ?

**Comment by thotheolh** [comment]
Also I am running in SPV mode when the OutOfMemory exception happened.

**Comment by schildbach** [comment]
Use a heap analyzer to find out what's needing the memory.

**Comment by nnmix** [comment]
increase program's memory allocation as needed, 
e.g. 6GB max heap size: -Xmx6144m 
JVM  options (JAVA_OPTS)  -Xmx<size> to set maximum Java heap size
