### ISSUE TITLE
Send from basic wallet causes IllegalStateException

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1747]
(stacktrace from the bitcoinj mailing list)
java.lang.IllegalStateException: doesn't support deterministic chains
    at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
    at org.bitcoinj.wallet.KeyChainGroup.getActiveKeyChain(KeyChainGroup.java:426)
    at org.bitcoinj.wallet.KeyChainGroup.currentAddress(KeyChainGroup.java:308)
    at org.bitcoinj.wallet.Wallet.currentAddress(Wallet.java:607)
    at org.bitcoinj.wallet.Wallet.currentChangeAddress(Wallet.java:861)
    at org.bitcoinj.wallet.Wallet.calculateFee(Wallet.java:5062)
    at org.bitcoinj.wallet.Wallet.completeTx(Wallet.java:4151)
    at org.bitcoinj.wallet.Wallet.sendCoinsOffline(Wallet.java:3948)
    at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:4015)
    at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:3984)

We should create a testcase specifically for this case. And make sure it doesn't try to get a deterministically derived change address. Instead, send change back to the address it came from?

**Comment by ckpenep** [comment]
I have the same error. Has anyone solved this?

**Comment by schildbach** [comment]
A basic wallet doesn't have any deterministic chains. It is meant to manually import keys. Is that what you want to do?

For most wallet usecases, I would recommend to use `Wallet.createDeterministic()` and let bitcoinj handle address generation for you.

**Comment by schildbach** [comment]
To anyone who is/was affected by this: Is this still happening with 0.17? I've got some code which sends from a paper wallet (using a basic wallet) and it doesn't throw this exception.

**Comment by schildbach** [comment]
I assume this is fixed.
