### ISSUE TITLE
KeyChainGroupTest.bloom does not adequately test bloom filters

### ISSUE THREAD

**Issue by matthewleon** [bitcoinj/bitcoinj#1804]
Even if the code in question is being tested correctly, the bloom filter will cause tests to fail, on rare occasion, through false positives:

https://github.com/bitcoinj/bitcoinj/blob/59a6407e68288dc28ecc583e20d112f7f8882aa3/core/src/test/java/org/bitcoinj/wallet/KeyChainGroupTest.java#L340

A correct test should actually hit the bloom filter with enough fuzzed data to make a statistically valid determination regarding its false-positive rate, and ensure zero false-negative rate.

**Comment by matthewleon** [comment]
Arguably, the testing in question should actually be happening in `BloomFilterTest`.

**Comment by schildbach** [comment]
I guess I agree with both.

**Comment by schildbach** [comment]
A more recent occurence of this problem, mentioned in #2029 :

```
2020-08-26T18:07:12.8307130Z org.bitcoinj.wallet.BasicKeyChainTest > bloom FAILED
2020-08-26T18:07:12.8307510Z     java.lang.AssertionError
2020-08-26T18:07:12.8311030Z         at org.junit.Assert.fail(Assert.java:87)
2020-08-26T18:07:12.8311490Z         at org.junit.Assert.assertTrue(Assert.java:42)
2020-08-26T18:07:12.8312000Z         at org.junit.Assert.assertFalse(Assert.java:65)
2020-08-26T18:07:12.8312740Z         at org.junit.Assert.assertFalse(Assert.java:75)
2020-08-26T18:07:12.8314380Z         at org.bitcoinj.wallet.BasicKeyChainTest.bloom(BasicKeyChainTest.java:261)
2020-08-26T18:07:29.5192230Z 
2020-08-26T18:07:29.5192710Z 23324 tests completed, 1 failed, 6003 skipped
```

Test source is here: https://github.com/bitcoinj/bitcoinj/blob/master/core/src/test/java/org/bitcoinj/wallet/BasicKeyChainTest.java#L248-L262

Is this caused by `ECKey key3 = new ECKey()` randomly being a "false positive"?  (the false positive rate is `0.001` in the test).
