### ISSUE TITLE
Exception while syncing Blockchain: org.bitcoinj.net.ConnectionHandler] Error handling SelectionKey: java.nio.channels.CancelledKeyException

### ISSUE THREAD

**Issue by Tockra** [bitcoinj/bitcoinj#2021]
Hi,

I always get the following exception while syncing the blockchain. It appears often when I start a freshly sync, but it appears later too (but not so often).

The sync seems to work, but it isn't really cool to have a lot of Stacktraces of exceptions in my program console:
```bash
[10:53:13 INFO]: [org.bitcoinj.core.PeerGroup] [5.9.68.19]:8333: Peer died      (8 connected, 4 pending, 12 max)
[10:53:13 INFO]: [org.bitcoinj.core.listeners.DownloadProgressTracker] Chain download 35% done with 56713 blocks to go, block date 2019-07-25T12:15:20Z
[10:53:13 INFO]: [org.bitcoinj.core.listeners.DownloadProgressTracker] Chain download 36% done with 55840 blocks to go, block date 2019-07-30T23:15:06Z
[10:53:13 INFO]: [org.bitcoinj.core.Peer] Peer{[51.81.13.149]:8333, version=70015, subVer=/Satoshi:0.20.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:53:13, height=643667}
[10:53:13 INFO]: [org.bitcoinj.core.PeerGroup] Peer{[51.81.13.149]:8333, version=70015, subVer=/Satoshi:0.20.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:53:13, height=643667}: New peer      (9 connected, 3 pending, 12 max)
[10:53:13 INFO]: [org.bitcoinj.core.Peer] Peer{[51.81.13.149]:8333, version=70015, subVer=/Satoshi:0.20.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:53:13, height=643667}: Peer does not support bloom filtering.
[10:53:13 INFO]: [org.bitcoinj.core.PeerGroup] [51.81.13.149]:8333: Peer died      (8 connected, 3 pending, 12 max)
[10:53:13 INFO]: [org.bitcoinj.core.PeerGroup] Waiting 1000 ms before next connect attempt to [76.126.246.139]:8333
[10:53:13 WARN]: [org.bitcoinj.net.ConnectionHandler] Error handling SelectionKey: java.nio.channels.CancelledKeyException
app    | java.nio.channels.CancelledKeyException: null
app    | 	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:74) ~[?:?]
app    | 	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:133) ~[?:?]
app    | 	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:378) ~[?:?]
app    | 	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[?:?]
app    | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[?:?]
app    | 	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Here the code:
```java
        NetworkParameters params = MainNetParams.get();
        this.walletKit = new WalletAppKit(params,new File(config.getWalletPath()),"btc");
        this.walletKit.setBlockingStartup(false);
        this.walletKit.startAsync();
        this.walletKit.awaitRunning();
```

I'm using Java 14 and I run the application in a docker container: `openjdk:14-alpine`

T

**Comment by Tockra** [comment]
Here a second position of the console:
```bash
[10:54:49 INFO]: [org.bitcoinj.core.PeerGroup] Waiting 999 ms before next connect attempt to [87.151.0.209]:8333
[10:54:50 INFO]: [org.bitcoinj.core.PeerGroup] Attempting connection to [83.163.211.75]:8333     (11 connected, 1 pending, 12 max)
[10:54:50 INFO]: [org.bitcoinj.net.NioClientManager] Connected to seed.btc.petertodd.org/83.163.211.75:8333
[10:54:50 INFO]: [org.bitcoinj.core.Peer] Announcing to seed.btc.petertodd.org/83.163.211.75:8333 as: /bitcoinj:0.15.7/
[10:54:50 INFO]: [org.bitcoinj.core.Peer] Peer{[83.163.211.75]:8333, version=70015, subVer=/Satoshi:0.17.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:54:57, height=643667}
[10:54:50 INFO]: [org.bitcoinj.core.PeerGroup] Peer{[83.163.211.75]:8333, version=70015, subVer=/Satoshi:0.17.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:54:57, height=643667}: New peer      (12 connected, 0 pending, 12 max)
[10:54:50 INFO]: [org.bitcoinj.core.Peer] Peer{[83.163.211.75]:8333, version=70015, subVer=/Satoshi:0.17.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2020-08-14 10:54:57, height=643667}: Sending Bloom filter and querying mempool
[10:55:21 INFO]: [org.bitcoinj.core.PeerGroup] [210.16.100.166]:8333: Peer died      (12 connected, 0 pending, 12 max)
[10:55:21 WARN]: [org.bitcoinj.net.NioClientManager] Failed to connect with exception: java.nio.channels.ClosedChannelException: null
app    | java.nio.channels.ClosedChannelException: null
app    | 	at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:165) ~[?:?]
app    | 	at sun.nio.ch.SocketChannelImpl.beginFinishConnect(SocketChannelImpl.java:792) ~[?:?]
app    | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:838) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[?:?]
app    | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[?:?]
app    | 	at java.lang.Thread.run(Thread.java:832) [?:?]
[10:55:23 INFO]: [org.bitcoinj.core.PeerGroup] [201.244.233.115]:8333: Peer died      (12 connected, 0 pending, 12 max)
[10:55:23 WARN]: [org.bitcoinj.net.NioClientManager] Failed to connect with exception: java.nio.channels.ClosedChannelException: null
app    | java.nio.channels.ClosedChannelException: null
app    | 	at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:165) ~[?:?]
app    | 	at sun.nio.ch.SocketChannelImpl.beginFinishConnect(SocketChannelImpl.java:792) ~[?:?]
app    | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:838) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64) ~[?:?]
app    | 	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[?:?]
app    | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[patched_1.16.1.jar:git-Paper-"0b33230f2"]
app    | 	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[?:?]
app    | 	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by schildbach** [comment]
These exceptions are typical for connection problems to the remote server, e.g. a dropped connection or bad connectivity in general.

Basically you can ignore them as long as your blockchain sync is continuing.

**Comment by Tockra** [comment]
If it is normal, maybe you should remove the Stack trace from the output?
