### ISSUE TITLE
'Peer died' error when running example in regtest mode

### ISSUE THREAD

**Issue by humbcezar** [bitcoinj/bitcoinj#2042]
I tried to execute the example in file examples/src/main/java/org/bitcoinj/examples/ForwardingService.java. The following error appeared in release 0.15.7, and 0.15.8, but worked as expected in 0.15.6. The error happens only when I run it with the flag regtest.

> /usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/snap/intellij-idea-community/249/lib/idea_rt.jar=33491:/snap/intellij-idea-community/249/bin -Dfile.encoding=UTF-8 -classpath /bitcoin-projects/bitcoinj-get-started/target/classes:/.m2/repository/org/bitcoinj/bitcoinj-core/0.15.8/bitcoinj-core-0.15.8.jar:/.m2/repository/org/bouncycastle/bcprov-jdk15to18/1.63/bcprov-jdk15to18-1.63.jar:/m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar:/.m2/repository/com/squareup/okhttp3/okhttp/3.12.8/okhttp-3.12.8.jar:/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar:/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar:/.m2/repository/com/google/guava/guava/29.0-jre/guava-29.0-jre.jar:/m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/.m2/repository/org/checkerframework/checker-qual/2.11.1/checker-qual-2.11.1.jar:/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar:/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/m2/repository/org/slf4j/slf4j-simple/1.7.22/slf4j-simple-1.7.22.jar bitcoinj_get_started.Main mwAtekhsmaRmynPo6YmFkLrn8CJC82tmr7 regtest
Network: org.bitcoin.regtest
Forwarding address: mwAtekhsmaRmynPo6YmFkLrn8CJC82tmr7
[main] INFO org.bitcoinj.core.Context - Creating bitcoinj 0.15.8 context.
[WalletAppKit STARTING] INFO org.bitcoinj.kits.WalletAppKit - Starting up with directory = .
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[WalletAppKit STARTING] INFO org.bitcoinj.core.AbstractBlockChain - chain head is at height 304:
 block: 
   hash: 2049aad6095e44ca808366429be2f00d81c8aabc7395bb7612002386e2967842
   version: 805306368 (BIP34, BIP66, BIP65)
   previous block: 66fc896264d723b99d718b078e9079fd667f4e7e32f8a70365b44ee1a3396bbb
   time: 1599454140 (2020-09-07T04:49:00Z)
   difficulty target (nBits): 545259519
   nonce: 3
[WalletAppKit STARTING] INFO org.bitcoinj.wallet.Wallet - New broadcaster so uploading waiting tx 5546e4952ef7922dc3be7c007a8a68c3ed7c2e747a3fa8dfa233b27a60441ee5
[WalletAppKit STARTING] INFO org.bitcoinj.core.TransactionBroadcast - Waiting for 1 peers required for broadcast, we have 0 ...
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Starting ...
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Localhost peer detected, trying to use it instead of P2P discovery
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 0 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to localhost/127.0.0.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to localhost/127.0.0.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:28, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:28, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:28, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 999 ms before next connect attempt to [127.0.1.1]:18444
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.1.1]:18444     (0 connected, 1 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to System-Product-Name/127.0.1.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to System-Product-Name/127.0.1.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:29, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:29, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:29, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.1.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [127.0.0.1]:18444
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to localhost/127.0.0.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to localhost/127.0.0.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:30, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:30, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:30, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [127.0.1.1]:18444
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.1.1]:18444     (0 connected, 1 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to System-Product-Name/127.0.1.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to System-Product-Name/127.0.1.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:31, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:31, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:31, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.1.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [127.0.0.1]:18444
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to localhost/127.0.0.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to localhost/127.0.0.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:32, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:32, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:32, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [127.0.1.1]:18444
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "main" java.lang.IllegalStateException: Expected the service WalletAppKit [STOPPING] to be RUNNING, but was STOPPING
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:381)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:303)
	at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:164)
	at bitcoinj_get_started.Main.main(Main.java:86)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.1.1]:18444     (0 connected, 1 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to System-Product-Name/127.0.1.1:18444
[NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to System-Product-Name/127.0.1.1:18444 as: /bitcoinj:0.15.8/
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:33, height=304}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:33, height=304}: New peer      (1 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[127.0.1.1]:18444, version=70015, subVer=/Satoshi:0.20.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2020-09-07 14:01:33, height=304}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.1.1]:18444: Peer died      (0 connected, 0 pending, 1 max)
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 999 ms before next connect attempt to [127.0.0.1]:18444
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by schildbach** [comment]
I guess the reason is this:

```Peer does not support bloom filtering.```

Try to enable bloom filtering for your regtest node.

**Comment by msgilligan** [comment]
Use the `-peerbloomfilters=1` option to enable bloom filtering on your regtest node.
