### ISSUE TITLE
can not start to download BlockChain

### ISSUE THREAD

**Issue by yoSir** [bitcoinj/bitcoinj#2077]
I tried to run the [RestoreFromSeed.java](https://github.com/bitcoinj/bitcoinj/blob/master/examples/src/main/java/org/bitcoinj/examples/RestoreFromSeed.java), but it seems that it just keep connecting to new peers, but do not start to download BlockChain,  do you know the reason?

I added the DownloadProgressTracker as the listener, but I never see the message like `Chain download %d%% done with %d blocks to go, block date %s` in my log.

The following is part of my log:
```log
2020-12-31 13:19:40.052  INFO 43132 --- [ioClientManager] o.b.c.PeerGroup                          : [51.158.121.128]:18333: Peer died      (5 connected, 1 pending, 12 max)
2020-12-31 13:19:40.052  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 1000 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.053  WARN 43132 --- [ioClientManager] o.b.n.ConnectionHandler                  : Error handling SelectionKey: java.nio.channels.CancelledKeyException 

java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:74) ~[?:?]
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:133) ~[?:?]
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:378) ~[?:?]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244) [bitcoinj-core-0.15.9.jar:?]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.15.9.jar:?]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.15.9.jar:?]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-23.0.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [guava-23.0.jar:?]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) [bitcoinj-core-0.15.9.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

2020-12-31 13:19:40.232  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 820 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.235  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 817 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.235  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 817 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.679  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 373 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.679  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 373 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.679  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 373 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.680  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 372 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.688  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 364 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.689  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 363 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.693  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 359 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.693  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 359 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.699  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 353 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.705  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 347 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.710  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 342 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:40.792  INFO 43132 --- [ioClientManager] o.b.n.NioClientManager                   : Connected to seed.tbtc.petertodd.org/51.158.64.57:18333
2020-12-31 13:19:40.792  INFO 43132 --- [ioClientManager] o.b.c.Peer                               : Announcing to seed.tbtc.petertodd.org/51.158.64.57:18333 as: /bitcoinj:0.15.9/
2020-12-31 13:19:41.047  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 5 ms before next connect attempt to [118.190.132.240]:18333
2020-12-31 13:19:41.053  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Attempting connection to [118.190.132.240]:18333     (5 connected, 2 pending, 12 max)
2020-12-31 13:19:41.054  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Attempting connection to [118.190.132.240]:18333     (5 connected, 3 pending, 12 max)
2020-12-31 13:19:41.055  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Attempting connection to [212.47.252.122]:18333     (5 connected, 4 pending, 12 max)
2020-12-31 13:19:41.055  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Attempting connection to [51.158.121.128]:18333     (5 connected, 5 pending, 12 max)
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 2 peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 38 peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 34 peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.056  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 6 peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.056  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Peer discovery took 977.5 μs and returned 80 items from 1 discoverers
2020-12-31 13:19:41.056  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 61081 ms before next connect attempt to [46.101.189.209]:18333
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 2 peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 38 peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 34 peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.057  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 6 peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.057  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Peer discovery took 878.2 μs and returned 80 items from 1 discoverers
2020-12-31 13:19:41.057  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 61080 ms before next connect attempt to [163.172.49.123]:18333
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 2 peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 38 peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 34 peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.058  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 6 peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.059  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Peer discovery took 939.8 μs and returned 80 items from 1 discoverers
2020-12-31 13:19:41.059  INFO 43132 --- [eerGroup Thread] o.b.c.PeerGroup                          : Waiting 61078 ms before next connect attempt to [46.101.189.209]:18333
2020-12-31 13:19:41.060  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 2 peers from testnet-seed.bitcoin.jonasschnelli.ch
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 38 peers from seed.tbtc.petertodd.org
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 34 peers from seed.testnet.bitcoin.sprovoost.nl
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Requesting all peers from testnet-seed.bluematt.me
2020-12-31 13:19:41.061  INFO 43132 --- [NS seed lookups] o.b.n.d.DnsDiscovery                     : Got 6 peers from testnet-seed.bluematt.me
```

**Comment by yoSir** [comment]
After I changed the version of bitcoinj maven dependency to 0.15.6, it started to download the block chain. But the size of the file "restore-from-seed.spvchain" didn't change. I don't know why, and I don't know where does the data is stored. does the data is stored in memory but not the file?
<img width="360" alt="截屏2021-01-04 下午3 39 05" src="https://user-images.githubusercontent.com/29705291/103512155-39b91a00-4ea3-11eb-9fa1-eaf395b68808.png">

The following is part of my log:
2021-01-04 15:28:42.115  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 588000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:43.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 588000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
Checkpointing block 00000000001fab1bbbd681ab2ae221b677ad79ed837d792cc5b62ed6b7e6c253 at height 588672, time 2015-11-10T08:10:43Z
blockchain 31% completed, blocksSoFar: 1312556
2021-01-04 15:28:44.116  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 2000 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/156.25 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:45.119  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:46.115  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:47.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:48.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:49.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:50.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:51.117  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:52.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:53.116  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:54.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:55.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:56.116  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:57.114  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
Checkpointing block 0000000000a133fb2aa6ae4b8ea86ce2b31a1085bfb962c1c058e4cff0293e7d at height 590688, time 2015-11-10T08:57:55Z
2021-01-04 15:28:58.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 2000 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/156.25 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:59.117  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:00.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:01.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:02.117  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:03.117  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:04.118  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:05.119  INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)

**Comment by yoSir** [comment]
After I changed the version of bitcoinj maven dependency to 0.15.6, it started to download the block chain. But the size of the file "restore-from-seed.spvchain" didn't change. I don't know why, and I don't know where does the data is stored. does the data is stored in memory but not the file?
<img width="360" alt="截屏2021-01-04 下午3 39 05" src="https://user-images.githubusercontent.com/29705291/103512336-7c7af200-4ea3-11eb-82b4-d4f0d5308937.png">
The following is part of my log:
```
2021-01-04 15:28:42.115 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 588000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:43.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 588000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
Checkpointing block 00000000001fab1bbbd681ab2ae221b677ad79ed837d792cc5b62ed6b7e6c253 at height 588672, time 2015-11-10T08:10:43Z
blockchain 31% completed, blocksSoFar: 1312556
2021-01-04 15:28:44.116 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 2000 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/156.25 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:45.119 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:46.115 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:47.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:48.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:49.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:50.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:51.117 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:52.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:53.116 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:54.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:55.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:56.116 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:57.114 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 590000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
Checkpointing block 0000000000a133fb2aa6ae4b8ea86ce2b31a1085bfb962c1c058e4cff0293e7d at height 590688, time 2015-11-10T08:57:55Z
2021-01-04 15:28:58.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 2000 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/156.25 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:28:59.117 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:00.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:01.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:02.117 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:03.117 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:04.118 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
2021-01-04 15:29:05.119 INFO 58604 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 15.63/0.00 kilobytes per sec, chain/common height 592000/1902261, stall disabled (threshold <0.78 KB/sec for 10 seconds)
```

**Comment by yoSir** [comment]
I have solved these problems. A fixed-size space is allocated to the file "restore-from-seed.spvchain" in advance. So although the file size has not changed, the content has changed.

**Comment by schildbach** [comment]
Thanks, good to hear!
