### ISSUE TITLE
org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 

### ISSUE THREAD

**Issue by zhanghuizong** [bitcoinj/bitcoinj#2130]
# Code
```java
TestNet3Params params = TestNet3Params.get();
WalletAppKit kit = new WalletAppKit(params, new File("."), "demo");
kit.connectToLocalHost();
kit.setAutoSave(false);
kit.startAsync();
kit.awaitRunning();
System.out.println(kit.wallet());
```

# Dependent version
```
<dependency>
    <groupId>org.bitcoinj</groupId>
    <artifactId>bitcoinj-core</artifactId>
    <version>0.15.9</version>
</dependency>
```

# Java version

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

# Exception

```
2021-08-05 14:50:34.721 INFO  [] [] org.bitcoinj.core.Context - Creating bitcoinj 0.15.9 context.
2021-08-05 14:50:34.756 INFO  [] [] org.bitcoinj.kits.WalletAppKit - Starting up with directory = .
2021-08-05 14:50:35.317 INFO  [] [] org.bitcoinj.crypto.MnemonicCode - PBKDF2 took 551.6 ms
2021-08-05 14:50:35.372 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - 1 keys needed for M/0H/0 = 1 issued + 0 lookahead size + 0 lookahead threshold - 0 num children
2021-08-05 14:50:35.373 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - Took 902.2 μs
2021-08-05 14:50:35.422 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - 133 keys needed for M/0H/0 = 1 issued + 100 lookahead size + 33 lookahead threshold - 1 num children
2021-08-05 14:50:35.465 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - Took 43.05 ms
2021-08-05 14:50:35.465 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - 133 keys needed for M/0H/1 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children
2021-08-05 14:50:35.490 INFO  [] [] org.bitcoinj.wallet.DeterministicKeyChain - Took 24.73 ms
2021-08-05 14:50:35.495 INFO  [] [] org.bitcoinj.store.SPVBlockStore - Creating new SPV block chain file .\demo.spvchain
2021-08-05 14:50:35.504 INFO  [] [] org.bitcoinj.core.CheckpointManager - Attempting to initialize a new block store with a checkpoint for time 1627541434 (2021-07-29T06:50:34Z)
2021-08-05 14:50:35.518 INFO  [] [] org.bitcoinj.core.CheckpointManager - Read 719 checkpoints up to time 2018-12-25T17:01:32Z, hash is 26940f1b442e9d2557a2dd9dd1ddf4cb08dd2d5fd05758542b9b852199d0ada2
2021-08-05 14:50:35.519 INFO  [] [] org.bitcoinj.core.AbstractBlockChain - chain head is at height 1449504:
 block: 
   hash: 000000000000013c89bd4e704bbfe26476f70d3e2881ca2c3553563fac07fd94
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 00000000000000f15b8a196b1c3568d14b5a7856da2fef7a7f5548266582ff28
   time: 1545757292 (2018-12-25T17:01:32Z)
   difficulty target (nBits): 436290249
   nonce: 2970861476

2021-08-05 14:50:35.544 INFO  [] [] org.bitcoinj.core.PeerGroup - Starting ...
2021-08-05 14:50:35.547 INFO  [] [] org.bitcoinj.core.PeerGroup - Localhost peer detected, trying to use it instead of P2P discovery
2021-08-05 14:50:35.555 INFO  [] [] org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.0.1]:18333     (0 connected, 1 pending, 0 max)
2021-08-05 14:50:35.557 INFO  [] [] org.bitcoinj.net.NioClientManager - Connected to localhost/127.0.0.1:18333
2021-08-05 14:50:35.557 INFO  [] [] org.bitcoinj.core.Peer - Announcing to localhost/127.0.0.1:18333 as: /bitcoinj:0.15.9/
2021-08-05 14:50:35.560 INFO  [] [] org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18333, version=70016, subVer=/Satoshi:0.21.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2021-08-05 14:50:36, height=2063321}
2021-08-05 14:50:35.562 INFO  [] [] org.bitcoinj.core.PeerGroup - Peer{[127.0.0.1]:18333, version=70016, subVer=/Satoshi:0.21.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2021-08-05 14:50:36, height=2063321}: New peer      (1 connected, 0 pending, 1 max)
2021-08-05 14:50:35.562 INFO  [] [] org.bitcoinj.core.Peer - Peer{[127.0.0.1]:18333, version=70016, subVer=/Satoshi:0.21.1/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2021-08-05 14:50:36, height=2063321}: Peer does not support bloom filtering.
2021-08-05 14:50:35.563 INFO  [] [] org.bitcoinj.core.PeerGroup - [127.0.0.1]:18333: Peer died      (0 connected, 0 pending, 1 max)
2021-08-05 14:50:35.563 INFO  [] [] org.bitcoinj.core.PeerGroup - Not yet setting download peer because there is no clear candidate.
2021-08-05 14:50:35.563 INFO  [] [] org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [172.16.7.94]:18333
2021-08-05 14:50:35.565 WARN  [] [] org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:244)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:65)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.lang.Thread.run(Thread.java:748)
2021-08-05 14:50:36.577 INFO  [] [] org.bitcoinj.core.PeerGroup - Attempting connection to [172.16.7.94]:18333     (0 connected, 1 pending, 1 max)
```

**Comment by schildbach** [comment]
Don't worry about the CancelledKeyException – it's just a bad connection to a peer.
