### ISSUE TITLE
Unit test org.bitcoinj.store.WalletProtobufSerializerTest::oneTx failing intermittently

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2161]
The unit test `org.bitcoinj.store.WalletProtobufSerializerTest::oneTx` is failing _intermittently_.

```
 org.bitcoinj.store.WalletProtobufSerializerTest > oneTx FAILED
     java.lang.AssertionError: expected:<2> but was:<4>
         at org.junit.Assert.fail(Assert.java:89)
         at org.junit.Assert.failNotEquals(Assert.java:835)
         at org.junit.Assert.assertEquals(Assert.java:647)
         at org.junit.Assert.assertEquals(Assert.java:633)
         at org.bitcoinj.store.WalletProtobufSerializerTest.oneTx(WalletProtobufSerializerTest.java:146)
```
For an example, see: https://github.com/bitcoinj/bitcoinj/runs/3486526841?check_suite_focus=true

The relevant code is here:
```
        Coin v1 = COIN;
        Transaction t1 = createFakeTx(UNITTEST, v1, myAddress);
        t1.getConfidence().markBroadcastBy(new PeerAddress(UNITTEST, InetAddress.getByName("1.2.3.4")));
        t1.getConfidence().markBroadcastBy(new PeerAddress(UNITTEST, InetAddress.getByName("5.6.7.8")));
        t1.getConfidence().setSource(TransactionConfidence.Source.NETWORK);
        myWallet.receivePending(t1, null);
        Wallet wallet1 = roundTrip(myWallet);
        assertEquals(1, wallet1.getTransactions(true).size());
        assertEquals(v1, wallet1.getBalance(Wallet.BalanceType.ESTIMATED));
        Transaction t1copy = wallet1.getTransaction(t1.getTxId());
        assertArrayEquals(t1.unsafeBitcoinSerialize(), t1copy.unsafeBitcoinSerialize());
        assertEquals(2, t1copy.getConfidence().numBroadcastPeers());
```

The final `assertEquals()` in the snippet is failing. Apparently when the wallet is duplicated by `roundTrip()` the two entries in `TransactionConfidence.broadcastBy` become four entries.

I suspect this might be because`PeerAddress::equals` contains the comparison `other.time == time`.

Given that `PeerAddress.time` is measured in seconds, in most unit test cases this will probably not show up, but if there is a significant real-time delay on a CI server instance or the test just happens to start near a 1-second boundary, a cloned `PeerAddress` and its original might appear different.

https://github.com/bitcoinj/bitcoinj/issues/1842 also may be a result of including `time` comparison in `PeerAddress::equals`

**Comment by msgilligan** [comment]
Draft PR #2163 _might_ fix this. It also contains an idea for an alternate possible fix.

**Comment by msgilligan** [comment]
I'm pretty sure PR #2163 fixed this. Closing.
