### ISSUE TITLE
Intermittent test failure:  bloomFilterForMarriedChains FAILED

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2174]
```
org.bitcoinj.wallet.KeyChainGroupTest > bloomFilterForMarriedChains FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.bitcoinj.wallet.KeyChainGroupTest.bloomFilterForMarriedChains(KeyChainGroupTest.java:392)

```

See: https://github.com/bitcoinj/bitcoinj/runs/3515126673?check_suite_focus=true

It is failing on the final assertion (`assertFalse`) in the test:

```
    @Test
    public void bloomFilterForMarriedChains() throws Exception {
        group = createMarriedKeyChainGroup();
        int bufferSize = group.getLookaheadSize() + group.getLookaheadThreshold();
        int expected = bufferSize * 2 /* chains */ * 2 /* elements */;
        assertEquals(expected, group.getBloomFilterElementCount());
        Address address1 = group.freshAddress(KeyChain.KeyPurpose.RECEIVE_FUNDS);
        assertEquals(expected, group.getBloomFilterElementCount());
        BloomFilter filter = group.getBloomFilter(expected + 2, 0.001, (long)(Math.random() * Long.MAX_VALUE));
        assertTrue(filter.contains(address1.getHash()));

        Address address2 = group.freshAddress(KeyChain.KeyPurpose.CHANGE);
        assertTrue(filter.contains(address2.getHash()));

        // Check that the filter contains the lookahead buffer.
        for (int i = 0; i < bufferSize - 1 /* issued address */; i++) {
            Address address = group.freshAddress(KeyChain.KeyPurpose.RECEIVE_FUNDS);
            assertTrue("key " + i, filter.contains(address.getHash()));
        }
        // We ran ahead of the lookahead buffer.
        assertFalse(filter.contains(group.freshAddress(KeyChain.KeyPurpose.RECEIVE_FUNDS).getHash()));
    }
```

**Comment by schildbach** [comment]
It's obviously a false positive of the bloom filter. We cannot guarantee that an element does _not_ match the filter.

We could try to make the filter more strict, so that a failure of the test becomes less probable.

**Comment by msgilligan** [comment]
`bloomFilterForMarriedChains` has been removed. We have reduced the number of false positives we're getting in our bloom filter tests and this is to some extend a duplicate of Issue #1984.
