### ISSUE TITLE
Tests: intermittent TestTimedOutException in FilteredBlockAndPartialMerkleTreeTests > serializeDownloadBlockWithWallet

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2175]
```
org.bitcoinj.core.FilteredBlockAndPartialMerkleTreeTests > serializeDownloadBlockWithWallet[1] FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 15 seconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:537)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:201)
        at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1233)
        at org.bitcoinj.core.PeerGroup.start(PeerGroup.java:1076)
        at org.bitcoinj.core.FilteredBlockAndPartialMerkleTreeTests.serializeDownloadBlockWithWallet(FilteredBlockAndPartialMerkleTreeTests.java:168)
```

See: https://github.com/bitcoinj/bitcoinj/runs/3515181687?check_suite_focus=true

@schildbach Should we increase the timeout again?

**Comment by fieder** [comment]
found the same when I run the first 

`gradle clean build`

for benchmark
![image](https://user-images.githubusercontent.com/1662253/138009587-61fb6b12-3157-48c2-bc49-33167aae2fd3.png)

![image](https://user-images.githubusercontent.com/1662253/138009496-2990e35d-694d-40b0-873d-08679e5f1528.png)

second time around it worked after killing a lot of my browser windows and Intellij instance I had running on the background

finally getting a 
`BUILD SUCCESSFUL in 1m 9s
32 actionable tasks: 30 executed, 2 up-to-date`
