### ISSUE TITLE
BlockFileLoader throws an exception for several dat files

### ISSUE THREAD

**Issue by vikulin** [bitcoinj/bitcoinj#2263]
```
Exception in thread "main" java.lang.RuntimeException: unexpected problem with block in blocks/rev00000.dat
        at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:168)
        at org.bitcoinj.utils.BlockFileLoader.hasNext(BlockFileLoader.java:98)
        at parser.App.main(App.java:45)
Caused by: java.lang.IllegalArgumentException: Out of range: 2708379452
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:206)
        at com.google.common.primitives.Ints.checkedCast(Ints.java:88)
        at org.bitcoinj.core.VarInt.intValue(VarInt.java:69)
        at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:165)
        at org.bitcoinj.core.Message.<init>(Message.java:85)
        at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:48)
        at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:146)
        at org.bitcoinj.core.Transaction.parseInputs(Transaction.java:693)
        at org.bitcoinj.core.Transaction.parse(Transaction.java:649)
        at org.bitcoinj.core.Message.<init>(Message.java:85)
        at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:48)
        at org.bitcoinj.core.Transaction.<init>(Transaction.java:245)
        at org.bitcoinj.core.Block.parseTransactions(Block.java:231)
        at org.bitcoinj.core.Block.parse(Block.java:255)
        at org.bitcoinj.core.Message.<init>(Message.java:85)
        at org.bitcoinj.core.Block.<init>(Block.java:158)
        at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:303)
        at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:81)
        at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:163)
        ... 2 more
```

**Comment by vikulin** [comment]
lib version 0.16.1

**Comment by schildbach** [comment]
Are you sure that your blocks database is not corrupt? A sciprt length of 2708379452 (bytes) seems  impossible to me.

The filename `rev00000.dat` seems to imply that this is the first (of many) blocks file, so we're likely talking about blocks more than 10 years old.

**Comment by vikulin** [comment]
> Are you sure that your blocks database is not corrupt? A sciprt length of 2708379452 (bytes) seems impossible to me.
> 
> The filename `rev00000.dat` seems to imply that this is the first (of many) blocks file, so we're likely talking about blocks more than 10 years old.

I used latest bitcoin core v22.0. I can double check it.

**Comment by Bloodmone** [comment]
On Fri, Jan 21, 2022 at 4:21 PM Vadym Vikulin ***@***.***>
wrote:

> lib version 0.16.1
>
> —ok
>
drop your private key let confirm

**Comment by vikulin** [comment]
solved by DB resync
