### ISSUE TITLE
A lot of org.bitcoinj.script.ScriptException errors received from TransactionInput.getScriptSig() method after 140000 block read

### ISSUE THREAD

**Issue by vikulin** [bitcoinj/bitcoinj#2266]
A lot of org.bitcoinj.script.ScriptException errors received from TransactionInput.getScriptSig() method after 140000 block read
My java code:
```
		BlockFileLoader bfl = new BlockFileLoader(np, new File("blocks"));
		Iterator<Block> bIter = bfl.iterator();
		Block block;
		while (true) {
			counter++;
			try {
				if(!bIter.hasNext()) {
					break;
				}
				block = bIter.next();
				
			} catch (Exception e) {
				continue;
			} finally {
				if(counter % 10000 == 0) {
					System.out.println(counter);
				}
			}
		
			List<Transaction> tx = null;
			try {
				tx = block.getTransactions();
			}catch (Exception e) {

			}
		    if(tx == null) {
		    	continue;
		    }
			for(Transaction t:tx) {
		        List<TransactionInput> inputs = t.getInputs();
		    	for(TransactionInput in:inputs) {

		    		try {
		    			Script scriptSig = in.getScriptSig();
```
Output:
```
140000
org.bitcoinj.script.ScriptException: Push of data element that is larger than remaining data: 41 vs 18
        at org.bitcoinj.script.Script.parse(Script.java:223)
        at org.bitcoinj.script.Script.<init>(Script.java:127)
        at org.bitcoinj.core.TransactionInput.getScriptSig(TransactionInput.java:196)
        at parser.App.main(App.java:70)
org.bitcoinj.script.ScriptException: Push of data element that is larger than remaining data: 72 vs 56
        at org.bitcoinj.script.Script.parse(Script.java:223)
        at org.bitcoinj.script.Script.<init>(Script.java:127)
        at org.bitcoinj.core.TransactionInput.getScriptSig(TransactionInput.java:196)
        at parser.App.main(App.java:70)
org.bitcoinj.script.ScriptException: Push of data element that is larger than remaining data: 68 vs 52
        at org.bitcoinj.script.Script.parse(Script.java:223)
        at org.bitcoinj.script.Script.<init>(Script.java:127)
        at org.bitcoinj.core.TransactionInput.getScriptSig(TransactionInput.java:196)
        at parser.App.main(App.java:70)
```

see:
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/script/Script.java#L223

**Comment by vikulin** [comment]
lib version 0.16.1

**Comment by msgilligan** [comment]
This may be a duplicate of Issue #1595.

@vikulin If you exclude Coinbase transactions (mining rewards) does the issue go away?
