### ISSUE TITLE
bitcoinj-tools:build_checkpoints FAILED

### ISSUE THREAD

**Issue by john-difool** [bitcoinj/bitcoinj#2287]
> cd bitcoinj/bitcoinj/tools
> gradle -q --no-daemon --console=plain --info build_checkpoints

...

Successfully started process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java''
Connecting to org.bitcoin.production, timeout 20 seconds...
java.util.concurrent.TimeoutException: Waited 20 seconds (plus 5255042 nanoseconds delay) for SettableFuture@1e4f4a5c[status=PENDING]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:121)
	at org.bitcoinj.tools.BuildCheckpoints.call(BuildCheckpoints.java:127)
	at org.bitcoinj.tools.BuildCheckpoints.call(BuildCheckpoints.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.bitcoinj.tools.BuildCheckpoints.main(BuildCheckpoints.java:69)

> Task :bitcoinj-tools:build_checkpoints FAILED
:bitcoinj-tools:build_checkpoints (Thread[Execution worker for ':',5,main]) completed. Took 21.628 secs.

**Comment by msgilligan** [comment]
I just tried on my (macOS, JDK 17.0.2) system and it seems to be working. The error looks like you might be having a networking connectivity issue:

```
Connecting to org.bitcoin.production, timeout 20 seconds...
java.util.concurrent.TimeoutException: Waited 20 seconds (plus 5255042 nanoseconds delay) for SettableFuture@1e4f4a5c[status=PENDING]
```

You could also try increasing the timeout.

**Comment by msgilligan** [comment]
@john-difool Any updates?
