### ISSUE TITLE
GitHub Actions: protobuf test failures due to `i` replaced by `ı`

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#2309]
Since a few days, our GitHub actions builds sometimes throw the following test failures. Here is a sample, but there are more of them, all very similar:

```
org.bitcoinj.wallet.DeterministicKeyChainTest > watchingSegwitChain FAILED
    org.junit.ComparisonFailure: expected:<...34\200H\366\312P"
      [issued_subkeys: 2
      lookahead_size: 10
      path: -2147483647
      path: 0
      sigs_required_to_spend: 1
    }
    public_key: "\002\237\202\357O\355r\020(]\235\b\3162\263N\331\320\216\246\262\376\260\352\224\313Bw\347~\310\336X"
    type: DETERMINISTIC_KEY

    deterministic_key {
      chain_code: "\336m6\270\332/\363\016\340=;\003\225\341S\024\262\332vM\201L\207\342\306=!\352A\f\272{"
      i]ssued_subkeys: 1
      l...> but was:<...34\200H\366\312P"
      [ıssued_subkeys: 2
      lookahead_size: 10
      path: -2147483647
      path: 0
      sigs_required_to_spend: 1
    }
    public_key: "\002\237\202\357O\355r\020(]\235\b\3162\263N\331\320\216\246\262\376\260\352\224\313Bw\347~\310\336X"
    type: DETERMINISTIC_KEY

    deterministic_key {
      chain_code: "\336m6\270\332/\363\016\340=;\003\225\341S\024\262\332vM\201L\207\342\306=!\352A\f\272{"
      ı]ssued_subkeys: 1
      l...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.bitcoinj.wallet.DeterministicKeyChainTest.checkSerialization(DeterministicKeyChainTest.java:771)
        at org.bitcoinj.wallet.DeterministicKeyChainTest.watchingSegwitChain(DeterministicKeyChainTest.java:546)
```

If comparing the "expected" and the "but was" parts, the only difference is the `i` in "issued_subkeys" is replaced by `ı`, the dotless `i`. Note the `i` in "sigs_required_to_spend" isn't changed this way, though it should be derived the same way – both are names of fields in our protobuf.

Afaik the output is generated by the protobuf library, so I'd investigate into that first.

**Comment by msgilligan** [comment]
This issue was noticed and discussed here: https://github.com/bitcoinj/bitcoinj/pull/2285#issuecomment-1059564438

I previously [commented](https://github.com/bitcoinj/bitcoinj/pull/2285#issuecomment-1059653942) on that thread that I haven't seen this problem on my macOS configuration (which matches one Github Actions config that was failing: macOS Big Sur, Java 17, Gradle 7.4), but it just happened on my macOS development system and seems to be intermittent.

**Comment by msgilligan** [comment]
Should we try testing with the latest protobuf?

**Comment by schildbach** [comment]
It's worth a try, albeit no bugfixes in the (Java) changelog. See https://github.com/bitcoinj/bitcoinj/pull/2314

**Comment by schildbach** [comment]
Didn't help. There is already one run with the issue: https://github.com/bitcoinj/bitcoinj/runs/5438882979

Is there a way to set the locale on GitHub Actions? I suspect GitHub has some virtual machines in their pool which are configured differently than the rest.

**Comment by msgilligan** [comment]
It's happening intermittently on my MacBook Pro, so it's not a simple CharSet config issue. Maybe it's memory corruption.

**Comment by msgilligan** [comment]
I'm trying to think of what we have changed recently (Gradle 7.4?) that might be causing (or contributing to) this...

**Comment by schildbach** [comment]
More observations. It doesn't seem to be restricted to the OS, here is a failed Ubuntu run: https://github.com/bitcoinj/bitcoinj/runs/5432270990

Also the Java version is not important. Both 11 and 17 are affected.

@msgilligan What Java distro have you used when it happened on your Mac?

The only thing I can say is that Debian/Ubuntu OpenJDK is not affected for now.

**Comment by schildbach** [comment]
The thing about the memory corruption thesis is that I would not expect it to happen in always the same way. Also the relationship of the two i's strongly point to _some_ locale issue imho.

**Comment by schildbach** [comment]
I just looked through old failed runs and could not find any that have the issue. However I've re-run a lot of runs in the past, so I can't assert that have not happened at all. Maybe I should not re-run in future.

**Comment by msgilligan** [comment]
> I just looked through old failed runs and could not find any that have the issue. However I've re-run a lot of runs in the past, so I can't assert that have not happened at all. Maybe I should not re-run in future.

I think re-running is ok, as long as you look at the failure (and maybe even make sure there's an issue for it)

**Comment by msgilligan** [comment]
> @msgilligan What Java distro have you used when it happened on your Mac?

Temurin. (and I've only seen it fail once)

Maybe we could try a different distro on Github Actions.

**Comment by msgilligan** [comment]
> > Maybe we could try a different distro on Github Actions.
> 
> Sure. Do you have a suggestion? I don't know much besides OpenJDK.

Well these are the easy choices:

https://github.com/actions/setup-java#supported-distributions

I'll try one or more of these on a branch.

**Comment by msgilligan** [comment]
I submitted draft PR #2315 (with a total of 19 jobs!) and this error did not occur -- though 3 others did. Maybe should try re-running it a few times.

(I also submitted PR #2316 to update to the latest setup-java action as I noticed we were behind and I think the newer versions add more JDK choices)

I also pushed f1ca84751d0c2646d85ff328f4f22074a850f02d to revert to Gradle 7.3.3.

**Comment by msgilligan** [comment]
Here is the failure with Gradle 7.3.3 and the Microsoft JDK17:

https://github.com/msgilligan/bitcoinj/runs/5440185303?check_suite_focus=true

**Comment by msgilligan** [comment]
Current status:
```
for (( ; ; )) ; do gradle bitcoinj-core:cleanTest bitcoinj-core:test --tests org.bitcoinj.wallet.DeterministicKeyChainTest ; done
```

**Comment by msgilligan** [comment]
> If comparing the "expected" and the "but was" parts, the only difference is the `i` in "issued_subkeys" is replaced by `ı`, the dotless `i`. 

When I look at the file `watching-wallet-p2wpkh-serialization.txt` I don't see the `[` or `]` characters that I see in the output above. Why are those characters showing up in the output?

**Comment by msgilligan** [comment]
I took a look at the `checkSerialization` method and made a PR to clean it up a little bit: https://github.com/bitcoinj/bitcoinj/pull/2317

I also noticed the following warning in the JavaDoc for  `GeneratedMessageLite::toString`:

> The first line of the `toString()` representation includes a commented version of `super.toString()` to act as an indicator that this should not be relied on for comparisons.

**Comment by msgilligan** [comment]
> Current status:
> 
> ```
> for (( ; ; )) ; do gradle bitcoinj-core:cleanTest bitcoinj-core:test --tests org.bitcoinj.wallet.DeterministicKeyChainTest ; done
> ```

I'm having a hard time reproducing the issue (on my laptop) with variations of the above script. (In fact the issue has only happened once on my laptop.) I'm wondering if the "corruption" is happening intermittently during the build process not during the running of the tests...

**Comment by schildbach** [comment]
> > If comparing the "expected" and the "but was" parts, the only difference is the `i` in "issued_subkeys" is replaced by `ı`, the dotless `i`.
> 
> When I look at the file `watching-wallet-p2wpkh-serialization.txt` I don't see the `[` or `]` characters that I see in the output above. Why are those characters showing up in the output?

I believe the brackets are inserted by `assertEquals` to highlight the parts being compared.

**Comment by msgilligan** [comment]
This one seems to have disappeared!

**Comment by msgilligan** [comment]
@schildbach I'm closing this as it seems to have disappeared years ago.
