### ISSUE TITLE
CycleDetectingLockFactory$PotentialDeadlockException: Wallet lock -> PeerGroup lock, PeerGroup lock -> Wallet lock

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#2398]
Just got this error when building locally (Ubuntu 20.04, Gradle 4.4.1, openjdk 11.0.14.1). I've never seen this before, and it went away already with the next build.

```
org.bitcoinj.core.FilteredBlockAndPartialMerkleTreeTest > serializeDownloadBlockWithWallet[1] FAILED
    com.google.common.util.concurrent.CycleDetectingLockFactory$PotentialDeadlockException: Wallet lock -> PeerGroup lock, PeerGroup lock -> Wallet lock
        at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:772)
        at org.bitcoinj.core.PeerGroup.connectTo(PeerGroup.java:1331)
        at org.bitcoinj.testing.TestWithPeerGroup.connectPeerWithoutVersionExchange(TestWithPeerGroup.java:121)
        at org.bitcoinj.testing.TestWithPeerGroup.connectPeer(TestWithPeerGroup.java:133)
        at org.bitcoinj.testing.TestWithPeerGroup.connectPeer(TestWithPeerGroup.java:128)
        at org.bitcoinj.core.FilteredBlockAndPartialMerkleTreeTest.serializeDownloadBlockWithWallet(FilteredBlockAndPartialMerkleTreeTest.java:169)

        Caused by:
        com.google.common.util.concurrent.CycleDetectingLockFactory$ExampleStackTrace: PeerGroup lock -> Wallet lock
            at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:772)
            at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5198)
            at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1127)
            at org.bitcoinj.testing.TestWithPeerGroup.initPeerGroup(TestWithPeerGroup.java:91)
            at org.bitcoinj.testing.TestWithPeerGroup.setUp(TestWithPeerGroup.java:70)
            at org.bitcoinj.core.FilteredBlockAndPartialMerkleTreeTest.setUp(FilteredBlockAndPartialMerkleTreeTest.java:68)
```

**Comment by msgilligan** [comment]
This just occurred in a test.

![Image](https://github.com/user-attachments/assets/e59a4d18-eb03-4669-9aea-3898bb4ad918)
