### ISSUE TITLE
fromString() can't handle bech32 type address

### ISSUE THREAD

**Issue by sj602** [bitcoinj/bitcoinj#2660]
Hi, I'm using bitcoinj 0.16.1 

As you see below fromString() method is designed to parsing base58 address first,
and if there's AddressFormatException, it tries to parse bech32 Address afterwards.

```
public static Address fromString(@Nullable NetworkParameters params, String str)
            throws AddressFormatException {
        try {
            return LegacyAddress.fromBase58(params, str);
        } catch (AddressFormatException.WrongNetwork x) {
            throw x;
        } catch (AddressFormatException x) {
            try {
                return SegwitAddress.fromBech32(params, str);
            } catch (AddressFormatException.WrongNetwork x2) {
                throw x;
            } catch (AddressFormatException x2) {
                throw new AddressFormatException(str);
            }
        }
    }
```

but it only throws AddressFormatException(InvalidCharacter) and stop. Nothing happens to the next.
```
Caused by: org.bitcoinj.core.AddressFormatException$InvalidCharacter: Invalid character '0' at position 20
	at org.bitcoinj.core.Base58.decode(Base58.java:132)
	at org.bitcoinj.core.Base58.decodeChecked(Base58.java:171)
	at org.bitcoinj.core.LegacyAddress.fromBase58(LegacyAddress.java:126)
	at org.bitcoinj.core.Address.fromString(Address.java:58)
```

my test address is `tb1qatp9p3c5a6ur8uz20ug52c3cqpsxame6t4rjmj`

**Comment by schildbach** [comment]
Can you post your test?

**Comment by sj602** [comment]
I found that it works as I expected with this,
`fromString(null, "tb1qatp9p3c5a6ur8uz20ug52c3cqpsxame6t4rjmj")`
so it returns SegwitAddress properly

but failed with this,
`fromString(networkParam, "tb1qatp9p3c5a6ur8uz20ug52c3cqpsxame6t4rjmj")`

The problem here is it parsed to SegwitAddress.fromBech32(address) properly (because it met AddressFormatException) but failed to hrp comparison below
```
public static SegwitAddress fromBech32(@Nullable NetworkParameters params, String bech32)
            throws AddressFormatException {
        Bech32.Bech32Data bechData = Bech32.decode(bech32);
        if (params == null) {
            for (NetworkParameters p : Networks.get()) {
                if (bechData.hrp.equals(p.getSegwitAddressHrp()))
                    return fromBechData(p, bechData);
            }
            throw new AddressFormatException.InvalidPrefix("No network found for " + bech32);
        } else {
            if (bechData.hrp.equals(params.getSegwitAddressHrp()))
                return fromBechData(params, bechData);
            throw new AddressFormatException.WrongNetwork(bechData.hrp);
        }
    }
```


hrp is not equals
```
Bech32.Bech32Data bechData = Bech32.decode(address);
System.out.println(bechData.hrp);
System.out.println(networkParameters.getSegwitAddressHrp());
```

returns
```
tb
bcrt
```


I found my param for `networkParam` is regtest mode.

**Comment by sj602** [comment]
Now I learned regtest's hrp is `bc` and testnet'shrp is `bcrp`
so it's different.

How do I change to testnet, not restest?

**Comment by sj602** [comment]
Sorry. it was my mistake
