### ISSUE TITLE
DefaultRiskAnalysisTest fails when run without a `Context` having been previously created.

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2691]
Since JUnit tests are not run in a deterministic order, this error is currently randomly occurring:

```
org.bitcoinj.wallet.DefaultRiskAnalysisTest > nonStandardDust FAILED
[476](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:479)
    java.lang.IllegalStateException: You must construct a Context object before using bitcoinj!
[477](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:480)
        at org.bitcoinj.core.Context.get(Context.java:124)
[478](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:481)
        at org.bitcoinj.core.Transaction.getConfidence(Transaction.java:1624)
[479](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:482)
        at org.bitcoinj.wallet.DefaultRiskAnalysis.analyzeIsFinal(DefaultRiskAnalysis.java:75)
[480](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:483)
        at org.bitcoinj.wallet.DefaultRiskAnalysis.analyze(DefaultRiskAnalysis.java:65)
[481](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:484)
        at org.bitcoinj.wallet.DefaultRiskAnalysisTest.nonStandardDust(DefaultRiskAnalysisTest.java:139)
[482](https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582#step:4:485)
```

See: https://github.com/bitcoinj/bitcoinj/actions/runs/4207671922/jobs/7302755582

The problem can easily be reproduced by running `DefaultRiskAnalysisTest` as a standalone test.

**Comment by schildbach** [comment]
Fixed via e27baa1.
