### ISSUE TITLE
having a hard time building a checkpoints.txt file using build-checkpoints in tools getting difficulty target is bad

### ISSUE THREAD

**Issue by bitnet-io** [bitcoinj/bitcoinj#2764]
my copy of bitnet-qt uses 1e0ffff0 for the genesis block bits even though the CScript is set to 1d00ffff

fork of bitcoinj
https://github.com/bitnet-io/exchangej

# using bitnet-qt and bitnet-cli
https://github.com/bitnet-io/bitnet-core
./tools/build-checkpoints --net=MAIN --days=0 --peer=127.0.0.1

same as in genesis block in bitnet-cli getblockhash 0
maxTarget = Utils.decodeCompactBits(0x1e0ffff0L);

core/src/main/java/org/bitcoinj/params/MainNetParams.java 

1e0ffff0

Connecting to [127.0.0.1]:8333...
Checkpointing up to 2023-03-06T05:26:39Z

Checkpointing block 000003cabed542ff0ca23656c8e60dcc92fa26a9d89652ed0a0f744b518ad520 at height 240, time 2023-03-01T23:46:18Z
with bits   "bits": "1e0ffff0",

22:26:39 15 AbstractBlockChain.add: Failed to verify block: 
org.bitcoinj.core.VerificationException: Difficulty target is bad: 382960460855416404752349959655646619186102735082132602991180305108303872
	at org.bitcoinj.core.Block.getDifficultyTargetAsInteger(Block.java:537)
	at org.bitcoinj.core.Block.checkProofOfWork(Block.java:551)
	at org.bitcoinj.core.Block.verifyHeader(Block.java:723)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:439)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:332)
	at org.bitcoinj.core.Peer.processHeaders(Peer.java:671)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:488)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:147)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:829)
22:26:39 15 AbstractBlockChain.add: 00003410a3bf48d8b8a27ab86deae8d4011d226c86184bdc5c1557b046b21184

https://bitexplorer.io/block/00003410a3bf48d8b8a27ab86deae8d4011d226c86184bdc5c1557b046b21184
this is a block at height 411 00003410a3bf48d8b8a27ab86deae8d4011d226c86184bdc5c1557b046b21184 
with bits
"bits": "1e377ccb",

**Comment by bitnet-io** [comment]
program seems to loop over and over trying to add a block at height 411 but can not do it since the change in difficulty max target changes to build the checkpoints.txt file

**Comment by bitnet-io** [comment]
basically i get errors like this

org.bitcoinj.core.VerificationException: Could not verify block 0000201ea294491a9c7821e928323cdce3aa9f46aa1b749251e97d0b2be31b3b
FilteredBlock{merkleTree=PartialMerkleTree{transactionCount=1, matchedChildBits=[0], hashes=[d418317bcf6f7b4aa8893675f97738efd4848cf6f14f0425b62059c252adf8d5]}, header= block: 
   hash: 0000201ea294491a9c7821e928323cdce3aa9f46aa1b749251e97d0b2be31b3b
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 00000d8046dea79516bf108c3062b2c586107b44af5371c951770c8fbec3d8d8
   time: 1677714478 (2023-03-01T23:47:58Z)
   difficulty target (nBits): 506952907
   nonce: 384772
}
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:372)
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:170)
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1072)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:454)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:187)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.bitcoinj.core.VerificationException: Difficulty target is bad: 382960460855416404752349959655646619186102735082132602991180305108303872
	at org.bitcoinj.core.Block.getDifficultyTargetAsInteger(Block.java:537)
	at org.bitcoinj.core.Block.checkProofOfWork(Block.java:551)
	at org.bitcoinj.core.Block.verifyHeader(Block.java:723)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:439)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:361)
	... 11 common frames omitted

**Comment by bitnet-io** [comment]
//         maxTarget = Utils.decodeCompactBits(0x1e0ffff0L);
//        maxTarget = Utils.decodeCompactBits(0x1d00ffffL);
        maxTarget = Utils.decodeCompactBits(0x1a009f15L);


https://github.com/bitnet-io/exchangej/blob/main/core/src/main/java/org/bitcoinj/params/MainNetParams.java

**Comment by bitnet-io** [comment]
i need a value for maxTarget = Utils.decodeCompactBits(but for all values of all blocks) some blocks pass through others dont

**Comment by bitnet-io** [comment]
maxTarget = Utils.decodeCompactBits(0x207fFFFFL)
207fFFFF = 545259519

but the block is showing nbits value of 504365040

i changed these two values here -> 
https://github.com/bitnet-io/exchangej/blob/main/core/src/main/java/org/bitcoinj/core/Block.java#L117

https://github.com/bitnet-io/exchangej/blob/main/core/src/main/java/org/bitcoinj/params/MainNetParams.java#L36



but still getting errors like these about verifying the blocks and the exception?
org.bitcoinj.core.VerificationException: Could not verify block 000003cabed542ff0ca23656c8e60dcc92fa26a9d89652ed0a0f744b518ad520
FilteredBlock{merkleTree=PartialMerkleTree{transactionCount=1, matchedChildBits=[0], hashes=[5bd9ac54e28a5ca73bbdb2a02655f8cee5b794cf5272b35f1ed052075946151e]}, header= block: 
   hash: 000003cabed542ff0ca23656c8e60dcc92fa26a9d89652ed0a0f744b518ad520
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 0000085bf815183cebcdfa1f93449f0bb657be3e65bbdec13390716ce10b5c81
   time: 1677714378 (2023-03-01T23:46:18Z)
   difficulty target (nBits): 504365040
   nonce: 845880
}

**Comment by bitnet-io** [comment]
Caused by: org.bitcoinj.core.VerificationException: Unexpected change in difficulty at height 410: 1e377ccb vs 1e0ffff0
	at org.bitcoinj.params.AbstractBitcoinNetParams.checkDifficultyTransitions(AbstractBitcoinNetParams.java:90)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:468)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:361)
	... 6 common frames omitted

**Comment by schildbach** [comment]
Generally it's advised to post questions in our Matrix space. See https://bitcoinj.org/#community
