### ISSUE TITLE
Reduce (default) verbosity of PeerGroup logging.

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#3388]
PeerGroup logging is perhaps too verbose by default. We should probably do one or more of the following:

1. Change the default log level for the PeerGroup messages
2. Review the current log message and change the log level of certain messages
3. Possibly consider a context-specific verbosity flag for PeerGroup
4. Document how to adjust PeerGroup logging.

**Comment by msgilligan** [comment]
We've merged a handful of PRs that should help with this:

* PR #3590
* PR #3591
* PR #3592
* PR #3593
* PR #3594

**Comment by msgilligan** [comment]
I'm running WalletTemplate on MAINNET after merging the above PRs and they are definitely an improvement.

However, I'm still seeing at least two messages that seem unnecessarily verbose:

```
22:21:03.624 42 PeerGroup$2.go: Waiting 9999 ms before next connect attempt to [178.131.96.87]:18333
22:21:03.624 42 PeerGroup$2.go: Waiting 9999 ms before next connect attempt to [178.131.96.87]:18333
22:21:03.624 42 PeerGroup$2.go: Waiting 9999 ms before next connect attempt to [178.131.96.87]:18333
22:21:03.624 42 PeerGroup$2.go: Waiting 9999 ms before next connect attempt to [178.131.96.87]:18333
22:21:03.624 42 PeerGroup$2.go: Waiting 9999 ms before next connect attempt to [178.131.96.87]:18333
22:21:03.625 42 PeerGroup$2.go: Waiting 9998 ms before next connect attempt to [178.131.96.87]:18333
```

This one should probably be changed from `log.info` to `log.debug`.

And:

```
22:25:04.972 44 Peer.setBloomFilter: Peer{[72.211.1.222]:18333, version=70016, subVer=/Satoshi:25.0.0/, services=NETWORK, WITNESS, NETWORK_LIMITED, time=2025-02-19T22:25:05Z, height=3803483}: Peer does not support bloom filtering.
22:25:04.972 44 PeerGroup.handlePeerDeath: [72.211.1.222]:18333: Peer died      (6 connected, 19 pending, 12 max)
22:25:04.972 44 ConnectionHandler.writeBytes: Error writing message to connection, closing connection
java.nio.channels.CancelledKeyException
        at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:75)
        at java.base/sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:98)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:119)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:167)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:108)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.PeerGroup.handleNewPeer(PeerGroup.java:1665)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.PeerGroup$PeerStartupListener.onPeerConnected(PeerGroup.java:340)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.Peer.lambda$versionHandshakeComplete$3(Peer.java:575)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.Peer.versionHandshakeComplete(Peer.java:575)
        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:831)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526)
        at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:616)
        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:828)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2223)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.Peer.processVersionAck(Peer.java:567)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.Peer.processMessage(Peer.java:489)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:200)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:239)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:100)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.net.NioClientManager.run(NioClientManager.java:136)
        at com.google.common@33.4.0-android/com.google.common.util.concurrent.AbstractExecutionThreadService$1.lambda$doStart$1(AbstractExecutionThreadService.java:53)
        at com.google.common@33.4.0-android/com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:105)
        at org.bitcoinj.core@0.18-SNAPSHOT/org.bitcoinj.utils.ContextPropagatingThreadFactory.lambda$newThread$0(ContextPropagatingThreadFactory.java:49)
        at java.base/java.lang.Thread.run(Thread.java:1575)
22:25:04.972 44 PeerSocketHandler.exceptionCaught: [72.211.1.222]:18333 - java.nio.channels.CancelledKeyException
22:25:04.972 44 ConnectionHandler.handleKey: Error handling SelectionKey: java.nio.channels.CancelledKeyException: null
```

This one (`CancelledKeyException`) happens enough where maybe we don't need/want the stack trace?

**Comment by msgilligan** [comment]
(3) These two messages could probably be combined. (e.g. a single message that says that the peer died and why "Timed out")

```
22:30:01.095 50 PeerSocketHandler.timeoutOccurred: [178.176.79.216]:18333: Timed out
22:30:01.095 50 PeerGroup.handlePeerDeath: [178.176.79.216]:18333: Peer died      (8 connected, 8 pending, 12 max)
```

**Comment by msgilligan** [comment]
It might also be helpful to print summary information (how many peers we successfully attempted to connect to and how many were unsuccessful in an n-minute period. This summary information could be "info" level and the more detailed information could be "debug" level.

And the elephant in the room is that there are fewer and fewer MAINNET nodes that support Bloom Filters. One thing we could possibly do to get to a "quorum" sooner is to change our seed node resolution mechanism so that it finds nodes that have Bloom Filters enabled.

**Comment by schildbach** [comment]
The many redundant messages in case 1 seems like a bug to me.

**Comment by msgilligan** [comment]
It probably makes sense to write some documentation about how to manage and configure bitcoinj logging. Have a specification or design document that reviews the various use-cases, specifies defaults, and documents mechanisms and configurations for changing the logging for debugging various types of apps would probably be a good place to start.
