### ISSUE TITLE
Cannot connect to nodes after upgrading to 0.16.3

### ISSUE THREAD

**Issue by Winne599** [bitcoinj/bitcoinj#3420]
After discovering that we couldn't synchronize block 849137, we upgraded the package version of bitcoinj to 0.16.3 (we downloaded and uploaded the package to our own self-service since maven can't bring in packages directly and made some changes and added some implementations, but I don't think it should have affected the problem I'm experiencing), but after releasing it to the production environment, we found that we couldn't see the synchronized block information. It keeps trying to connect to the node and the connection fails with Network is unreachable , we don't know where we are running into the problem, can you help us out, is it because of the upgrade that the checkpoints are not working correctly?

```
**The error log is as follows:**
!!!!!!!! 2024:06:25 22:35:50.451 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3267 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.452 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3266 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:50.453 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:522 | Waiting 3265 ms before next connect attempt to [73.186.95.39]:8333 ********
!!!!!!!! 2024:06:25 22:35:53.718 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [73.186.95.39]:8333     (12 connected, 1 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.718 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [73.186.95.39]:8333     (12 connected, 2 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.718 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [73.186.95.39]:8333     (12 connected, 3 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.718 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [174.72.105.169]:8333     (12 connected, 4 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.719 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [174.72.105.169]:8333     (12 connected, 5 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.719 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [174.72.105.169]:8333     (12 connected, 6 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.719 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [174.72.105.169]:8333     (12 connected, 7 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.719 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [90.208.29.138]:8333     (12 connected, 8 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.719 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [90.208.29.138]:8333     (12 connected, 9 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [210.16.100.166]:8333     (12 connected, 10 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [210.16.100.166]:8333     (12 connected, 11 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [210.16.100.166]:8333     (12 connected, 12 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [210.16.100.166]:8333     (12 connected, 13 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [90.208.29.138]:8333     (12 connected, 14 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.720 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [13.211.79.130]:8333     (12 connected, 15 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [13.211.79.130]:8333     (12 connected, 16 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [13.211.79.130]:8333     (12 connected, 17 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [108.168.125.57]:8333     (12 connected, 18 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [108.168.125.57]:8333     (12 connected, 19 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [5.2.23.226]:8333     (12 connected, 20 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.721 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [165.22.235.29]:8333     (12 connected, 21 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [108.168.125.57]:8333     (12 connected, 22 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [176.104.37.122]:8333     (12 connected, 23 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [176.104.37.122]:8333     (12 connected, 24 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [176.104.37.122]:8333     (12 connected, 25 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [176.104.37.122]:8333     (12 connected, 26 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.722 | ctx-custodian | PeerGroup Thread | INFO  | org.bitcoinj.core.PeerGroup:1408 | Attempting connection to [2001:470:1f09:b14:0:0:0:11]:8333     (12 connected, 27 pending, 12 max) ********
!!!!!!!! 2024:06:25 22:35:53.723 | ctx-custodian | PeerGroup Thread | WARN  | org.bitcoinj.core.PeerGroup:1415 | Failed to connect to [2001:470:1f09:b14:0:0:0:11]:8333: Network is unreachable ********
```

**Comment by Winne599** [comment]
**also error log as follow:**

!!!!!!!! 2024:06:26 00:13:00.519 | ctx-custodian | NioClientManager | WARN  | org.bitcoinj.net.NioClientManager:80 | Failed to connect with exception: java.nio.channels.ClosedChannelException: null ********
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:160)
	at java.base/sun.nio.ch.SocketChannelImpl.beginFinishConnect(SocketChannelImpl.java:726)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:772)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50)
	at java.base/java.lang.Thread.run(Thread.java:834)
	
	
	
	
	
	can anyone help?

**Comment by schildbach** [comment]
You say the "checkpoints" might not be working correctly. Are you synching an existing wallet/chain, or are you starting a fresh one?

**Comment by schildbach** [comment]
@Winne599 If you post logs, can you use [\`\`\` code quotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to make them more readable? Thanks.

**Comment by schildbach** [comment]
> @Winne599 If you post logs, can you use [``` code quotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to make them more readable? Thanks.

I just noticed you tried, but only used on backtick instead of three (on a separate line).

**Comment by msgilligan** [comment]
`ClosedChannelException` happens regularly. It simply means that the connection to one node has been closed and `bitcoinj` recovers from that exception just fine (under normal conditions, at least)

The `Network is unreachable` exception can happen if the network give bitcoinj an invalid peer address, and bitcoinj should recover from that as well.

So I don't think the actual problem is related to either of those (non-fatal) exceptions.

**Comment by Winne599** [comment]
already resolved, just add maven <scope>compile</scope>, but I don't know why
