### ISSUE TITLE
null pointer handling in PeerAddress

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#703]
Originally reported on Google Code with ID 337

```
PeerAddress.addr and .services can be null.

However, this will lead to NPE in toString(), equals() and hashCode().

Here is one example of a user crash report:

java.lang.NullPointerException
at com.google.bitcoin.core.PeerAddress.hashCode(PeerAddress.java:248)
at java.util.HashMap.put(HashMap.java:390)
at java.util.HashSet.add(HashSet.java:95)
at com.google.bitcoin.core.PeerGroup.connectToAnyPeer(PeerGroup.java:479)
at com.google.bitcoin.core.PeerGroup.startUp(PeerGroup.java:508)
at com.google.common.util.concurrent.AbstractIdleService$1$1.run(AbstractIdleService.java:43)
at java.lang.Thread.run(Thread.java:856)
```

Reported by `andreas.schildbach` on 2013-03-06 19:56:20

**Comment by msgilligan** [comment]
Null-handling is causing problems (NPE) for I2P addresses which are currently being parsed so that `addr` and `hostname` are both `null`.

**Comment by msgilligan** [comment]
PR #2632 should resolve this issue.

**Comment by msgilligan** [comment]
@schildbach I think we can close this now that PR #2632 is merged.
