### ISSUE TITLE
Flake in full verification tests on b24

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#847]
Originally reported on Google Code with ID 481

```
I'm not sure why these tests would ever be non deterministic, presumably there's a timing
issue lurking somewhere in the test infrastructure.

04:49:53 10 AbstractBlockChain.<init>: chain head is at height 0:
v1 block: 
   previous block: 0000000000000000000000000000000000000000000000000000000000000000
   merkle root: 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b
   time: [1384357791] Wed Nov 13 16:49:51 CET 2013
   difficulty target (nBits): 545259519
   nonce: 3

04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 6/block
40258585f05f5cd40821902fbe61dc4271ba51e70e44b12799cc4b23c92b5a74, but it did not cause
a reorganize:
105d74d995b745b80455d11b53b255187d65e893edc312d74895ef22db1d1133
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
6
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 035a07d54c5e575b01431924578c5f82781a560cdade23f94d101c8e1c0f3e9e
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 30a4a827c5190bae6d5c6dbcfef2142aae558c621e44f1123120147820acedb9
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 40258585f05f5cd40821902fbe61dc4271ba51e70e44b12799cc4b23c92b5a74
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 6/block
40258585f05f5cd40821902fbe61dc4271ba51e70e44b12799cc4b23c92b5a74, but it did not cause
a reorganize:
2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
6
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 30a4a827c5190bae6d5c6dbcfef2142aae558c621e44f1123120147820acedb9
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 37c493ae3395d4d2a669184ca89330088618aae67d154a7a9813e32173de542f
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 40258585f05f5cd40821902fbe61dc4271ba51e70e44b12799cc4b23c92b5a74
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 8/block
2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9, but it did not cause
a reorganize:
655961d8af44d4db9009fe37dd65f14a00f6839a09c2899fdfbe8d46db887de4
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
8
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 37c493ae3395d4d2a669184ca89330088618aae67d154a7a9813e32173de542f
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 5e4ef44756475b6b525296aac21c2c03ffe3e8547e528aa2e5150b877318eb18
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 8/block
2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9, but it did not cause
a reorganize:
31aba01c543c5064fba950ca801f2a58364c45a4313a760c0aabd7e48e85aa7c
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
8
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 37c493ae3395d4d2a669184ca89330088618aae67d154a7a9813e32173de542f
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 31aa390c603a343b2466fe7cb87db237e352af13ba91681637a4cd5f52f26acb
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9
04:49:53 10 AbstractBlockChain.add: Block does not connect: 7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97
prev 64a11580e8dadc5f5911b1cd7250450bf44493e945956fad67cb22ecf5502a33
04:49:53 10 AbstractBlockChain.add: Block does not connect: 7d66598d255670396e0a22e9a675af4da24515d0bac7e1f37a7f98b5ce53a4fb
prev 7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 8/block
2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9, but it did not cause
a reorganize:
64a11580e8dadc5f5911b1cd7250450bf44493e945956fad67cb22ecf5502a33
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
8
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 37c493ae3395d4d2a669184ca89330088618aae67d154a7a9813e32173de542f
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 2f1e188e7b56b3a922c49392ce6cf43bf8c68a1dfcb3b0843ba3c75a02306cf9
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 10/block
7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97, but it did not cause
a reorganize:
7d66598d255670396e0a22e9a675af4da24515d0bac7e1f37a7f98b5ce53a4fb
04:49:53 10 AbstractBlockChain.tryConnectingOrphans: Connected 1 orphan blocks.
04:49:53 10 AbstractBlockChain.add: Failed to verify block: 
com.google.bitcoin.core.VerificationException: Block had too many Signature Operations
    at com.google.bitcoin.core.Block.checkSigOps(Block.java:675)
    at com.google.bitcoin.core.Block.verifyTransactions(Block.java:793)
    at com.google.bitcoin.core.AbstractBlockChain.add(AbstractBlockChain.java:363)
    at com.google.bitcoin.core.AbstractBlockChain.add(AbstractBlockChain.java:239)
    at com.google.bitcoin.core.FullPrunedBlockChainTest.testGeneratedChain(FullPrunedBlockChainTest.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
04:49:53 10 AbstractBlockChain.add: 697af72a838c56b0f5563ac34086616f2c2f50289a1032732bf1a650841ed716
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 10/block
7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97, but it did not cause
a reorganize:
1896e7233b8d7c0d254846ba1dc4595cc7e8ab863739f385314ec646243ac899
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
10
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 5c315057d96acb8beade815b3ed0c7a11a97bea6f1cc57a397cba248d61c745e
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 7dc7c5b4712a6a52eeade625dc017dad65b90509e050f9387c89c1e2c1f6332a
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97
04:49:53 10 AbstractBlockChain.connectBlock: Block forks the chain at height 10/block
7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97, but it did not cause
a reorganize:
21f826c803bc4e78ddbf1f6027f8366bdda929ccd9b2509b6f1665a0e6c23c49
04:49:53 10 AbstractBlockChain.connectBlock: Block is causing a re-organize
04:49:53 10 AbstractBlockChain.handleNewBestChain: Re-organize after split at height
10
04:49:53 10 AbstractBlockChain.handleNewBestChain: Old chain head: 5c315057d96acb8beade815b3ed0c7a11a97bea6f1cc57a397cba248d61c745e
04:49:53 10 AbstractBlockChain.handleNewBestChain: New chain head: 1a9126265a56011af29a62f80e4b0446a9569271dbc546f8c2791df9f9fcfb4c
04:49:53 10 AbstractBlockChain.handleNewBestChain: Split at block: 7ae83705a6e86a81b84bbddb4e53cb5cd07885b8414e6e3b7e6b4d5a28a97f97
04:49:54 10 AbstractBlockChain.add: 19 blocks per second
04:49:54 10 AbstractBlockChain.connectBlock: Block forks the chain at height 11/block
5c315057d96acb8beade815b3ed0c7a11a97bea6f1cc57a397cba248d61c745e, but it did not cause
a reorganize:
483ba8db1a926798c70ac7de932378728d2f5b0d5d30a91cf840b37239dad42f
04:49:54 10 FullPrunedBlockChainTest.testGeneratedChain: Block didn't match connects
flag on block b24

java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.fail(Assert.java:95)
    at com.google.bitcoin.core.FullPrunedBlockChainTest.testGeneratedChain(FullPrunedBlockChainTest.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

```

Reported by `hearn@google.com` on 2013-11-13 15:55:24

**Comment by msgilligan** [comment]
@schildbach Is this still happening, can we close this one?

**Comment by schildbach** [comment]
I can't remember seeing this.
