### ISSUE TITLE
IllegalArgumentException: Invalid point compression

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#946]
Originally reported on Google Code with ID 580

```
java.lang.RuntimeException: Unable to create application de.schildbach.wallet.WalletApplication:
java.lang.IllegalArgumentException: Invalid point
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4155)
at android.app.ActivityThread.access$1300(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4747)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
This seems to be a regression with bitcoinj 0.12 (no reports so far for previous versions).
It keeps the app from loading so I only see it in the Google Play console.

Caused by: java.lang.IllegalArgumentException: Invalid point
at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
at org.spongycastle.math.ec.ECPoint.multiply(ECPoint.java:516)
at org.bitcoinj.crypto.DeterministicKey.<init>(DeterministicKey.java:72)
at org.bitcoinj.crypto.HDKeyDerivation.deriveChildKey(HDKeyDerivation.java:135)
at org.bitcoinj.crypto.DeterministicHierarchy.get$63f85a4(DeterministicHierarchy.java:93)
at org.bitcoinj.wallet.DeterministicKeyChain.initializeHierarchyUnencrypted(DeterministicKeyChain.java:310)
at org.bitcoinj.wallet.DeterministicKeyChain.<init>(DeterministicKeyChain.java:249)
at org.bitcoinj.wallet.DeterministicKeyChain.<init>(DeterministicKeyChain.java:186)
at org.bitcoinj.wallet.DeterministicKeyChain.<init>(DeterministicKeyChain.java:169)
at org.bitcoinj.wallet.DeterministicKeyChain.<init>(DeterministicKeyChain.java:152)
at org.bitcoinj.wallet.KeyChainGroup.createAndActivateNewHDChain(KeyChainGroup.java:228)
at org.bitcoinj.core.Wallet.<init>(Wallet.java:249)
at org.bitcoinj.core.Wallet.<init>(Wallet.java:215)
at de.schildbach.wallet.WalletApplication.loadWalletFromProtobuf(WalletApplication.java:296)
at de.schildbach.wallet.WalletApplication.onCreate(WalletApplication.java:130)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4152)
... 10 more
```

Reported by `andreas.schildbach` on 2014-10-10 12:44:23

**Comment by peterdettman** [comment]
Apologies for dropping out of this conversation earlier. Is it still a live issue? If so, the Genymotion report sounds promising; can we get a simple testcase that (even intermittently) reproduce this?

**Comment by schildbach** [comment]
It's a live issue, but only on several aging devices. The Motorola razr-i is the most prominent one. It got an OS update to 4.4 (from 4.1!) which apparently fixes the issue, but a couple of users don't care to update or can't update due to their carrier withholding the update.

I've not seen this on Android 4.4 and above. It's weird that the emulator image is affected.

**Comment by devinrsmith** [comment]
Just ran into this. IMO, `Script.parse(byte[] program)` should throw a ScriptException if the multisig is invalid. Alternatively, If the multisig is valid, then the multisig code code should be fixed.

```
Caused by: java.lang.IllegalArgumentException: Invalid point compression
        at org.spongycastle.math.ec.ECCurve$AbstractFp.decompressPoint(ECCurve.java:471)
        at org.spongycastle.math.ec.ECCurve.decodePoint(ECCurve.java:355)
        at org.bitcoinj.core.ECKey.fromPublicOnly(ECKey.java:311)
        at org.bitcoinj.script.Script.getPubKeys(Script.java:529)
```
The above is for transaction 109f6542cd03d855d8324db10499472c5fc3cd9d4d8dfef85676b4a135a09284.

It seems like the multisig *is* valid:

```json
{
  "value": 0.00011514,
  "n": 3,
  "scriptPubKey": {
    "asm": "1 04bdb3ce46e55a0a9c8eff156737616c02041dd6840db5b23edea387c106e410397c0114a2e98e9a89621c74d31bf6340d0eead9e84af3322a65ebdcefa8638e83 020843b3cff5cc1b4c579607b0e808cfe2d135d0e8a3570f227b4930724e041f22 2 OP_CHECKMULTISIG",
    "hex": "514104bdb3ce46e55a0a9c8eff156737616c02041dd6840db5b23edea387c106e410397c0114a2e98e9a89621c74d31bf6340d0eead9e84af3322a65ebdcefa8638e8321020843b3cff5cc1b4c579607b0e808cfe2d135d0e8a3570f227b4930724e041f2252ae",
    "reqSigs": 1,
    "type": "multisig",
    "addresses": [
      "1BYSkg9Wj6qcdifi2MQhgzbvQ4gNuF7aXn",
      "1NgoVcKdG42dxqXTqNNNwM5V3tNp8sN7Gh"
    ]
  }
}
```

**Comment by msgilligan** [comment]
@schildbach I'm closing this as these devices (and spongy castle) are no longer supported and the last comment on this issue is about 8 years old.
