### ISSUE TITLE
Payment Protocol tool is not accepting my payment request.

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#969]
Originally reported on Google Code with ID 603

```
Here is the error, the payment request was created with bitcoinj 12, I used my ssl pem
to create the keystore with the root certificate included in that pem, with my key.

I am using java 7, which some people said could be the problem.

Failed whilst retrieving payment URL: org.bitcoinj.protocols.payments.PaymentProtocolException$PkiVerificationException:
java.security.cert.CertPathValidatorException: Path does not chain with any of the
trust anchors
java.util.concurrent.ExecutionException: org.bitcoinj.protocols.payments.PaymentProtocolException$PkiVerificationException:
java.security.cert.CertPathValidatorException: Path does not chain with any of the
trust anchors
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at PaymentProtocolTool.dump(PaymentProtocolTool.java:57)
    at PaymentProtocolTool.main(PaymentProtocolTool.java:44)
Caused by: org.bitcoinj.protocols.payments.PaymentProtocolException$PkiVerificationException:
java.security.cert.CertPathValidatorException: Path does not chain with any of the
trust anchors
    at org.bitcoinj.protocols.payments.PaymentProtocol.verifyPaymentRequestPki(PaymentProtocol.java:234)
    at org.bitcoinj.protocols.payments.PaymentSession.<init>(PaymentSession.java:209)
    at org.bitcoinj.protocols.payments.PaymentSession$1.call(PaymentSession.java:178)
    at org.bitcoinj.protocols.payments.PaymentSession$1.call(PaymentSession.java:171)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with
any of the trust anchors
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:208)
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:279)
    at org.bitcoinj.protocols.payments.PaymentProtocol.verifyPaymentRequestPki(PaymentProtocol.java:199)
    ... 7 more
```

Reported by `gweedoBTC` on 2015-01-31 23:11:05

**Comment by msgilligan** [comment]
Payment Protocol tool was removed in PR #3613.
