### ISSUE TITLE
can't recover from illegalstateexception  when a block fork is being occured

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#972]
Originally reported on Google Code with ID 606

```
Block chain can not recover from illegal state exception after if any block fork is
being occure.

These are my app logs.

2015-02-23 15:10:14,206 [NioClientManager] INFO  core.AbstractBlockChain  - Block forks
the chain at height 344641/block 0000000000000000163e0b9535633c4b7febd7d816460316057250a9d01c5952,
but it did not cause a reorganize:
00000000000000000f503a6bbe7ddca7468e8ae50f611a2aeeaf8e478cf5ee29
2015-02-23 15:10:14,222 [NioClientManager] INFO  core.AbstractBlockChain  - Block is
causing a re-organize
2015-02-23 15:10:14,222 [NioClientManager] INFO  core.AbstractBlockChain  - Re-organize
after split at height 344641
2015-02-23 15:10:14,223 [NioClientManager] INFO  core.AbstractBlockChain  - Old chain
head: 00000000000000000f543ac474f0b8cdd8a9e37e29126d4efb27b70432799cba
2015-02-23 15:10:14,223 [NioClientManager] INFO  core.AbstractBlockChain  - New chain
head: 0000000000000000154d9593ca36c918186791cee47568bbd345085903b4d840
2015-02-23 15:10:14,223 [NioClientManager] INFO  core.AbstractBlockChain  - Split at
block: 0000000000000000163e0b9535633c4b7febd7d816460316057250a9d01c5952
2015-02-23 15:10:14,223 [NioClientManager] WARN  core.PeerSocketHandler  - [127.0.0.1]:8333
- 
java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:161)
    at com.google.bitcoin.core.Wallet.reorganize(Wallet.java:3429)
    at com.google.bitcoin.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:655)
    at com.google.bitcoin.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:489)
    at com.google.bitcoin.core.AbstractBlockChain.add(AbstractBlockChain.java:397)
    at com.google.bitcoin.core.AbstractBlockChain.tryConnectingOrphans(AbstractBlockChain.java:786)
    at com.google.bitcoin.core.AbstractBlockChain.add(AbstractBlockChain.java:401)
    at com.google.bitcoin.core.AbstractBlockChain.add(AbstractBlockChain.java:252)
    at com.google.bitcoin.core.Peer.processBlock(Peer.java:824)
    at com.google.bitcoin.core.Peer.processMessage(Peer.java:334)
    at com.google.bitcoin.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:139)
    at com.google.bitcoin.net.ConnectionHandler.handleKey(ConnectionHandler.java:216)
    at com.google.bitcoin.net.NioClientManager.handleKey(NioClientManager.java:74)
    at com.google.bitcoin.net.NioClientManager.run(NioClientManager.java:110)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
    at java.lang.Thread.run(Thread.java:745)

```

Reported by `deepak.agrawal@oodlestechnologies.com` on 2015-02-23 10:29:20

**Comment by jdojff** [comment]
Any news regarding this issue? Same here, wallet is stuck in the endless loop of error:

```
2015-08-25 09:34:08.570 INFO  [NioClientManager] AbstractBlockChain:508 - Block forks the chain at height 371308/block 000000000000000001953a15026db0a764d4c0c02c4db55f2d00c5d7b19e004a, but it did not cause a reorganize:
000000000000000008bb407830bac5af6185e24a138f74b7be1bf64f45baf17a
2015-08-25 09:34:08.570 INFO  [NioClientManager] AbstractBlockChain:818 - Connected orphan 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b
2015-08-25 09:34:08.570 INFO  [NioClientManager] AbstractBlockChain:487 - Block is causing a re-organize
2015-08-25 09:34:08.570 INFO  [NioClientManager] AbstractBlockChain:642 - Re-organize after split at height 371308
2015-08-25 09:34:08.571 INFO  [NioClientManager] AbstractBlockChain:643 - Old chain head: 00000000000000001109528a9e5b1d6ded0c55de68fe17830ec71525b358a72b
2015-08-25 09:34:08.571 INFO  [NioClientManager] AbstractBlockChain:644 - New chain head: 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b
2015-08-25 09:34:08.571 INFO  [NioClientManager] AbstractBlockChain:645 - Split at block: 000000000000000001953a15026db0a764d4c0c02c4db55f2d00c5d7b19e004a
2015-08-25 09:34:08.571 WARN  [NioClientManager] PeerSocketHandler:230 - [127.0.0.1]:8333 - : java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161) [guava-16.0.1.jar:]
	at org.bitcoinj.core.Wallet.reorganize(Wallet.java:4086) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:688) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:521) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:414) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.tryConnectingOrphans(AbstractBlockChain.java:819) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:418) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:165) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:342) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.13.1.jar:]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-16.0.1.jar:]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) [guava-16.0.1.jar:]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) [bitcoinj-core-0.13.1.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
```

**Comment by mikehearn** [comment]
Hmm. From looking at that assert, I'm going to guess there may have been an exception leaked out of a same-thread listener, or some other earlier crash. The assert is saying that it appears a previous reorganize operation was interrupted half way through. But I don't see any other stack trace in your logs.

**Comment by jdojff** [comment]
Ok, initial error message is bellow, new thing here is *Block does not connect: 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b prev 000000000000000008bb407830bac5af6185e24a138f74b7be1bf64f45baf17a*
No other errors occur before this.

```
2015-08-24 13:13:55.856 WARN  [NioClientManager] AbstractBlockChain:407 - Block does not connect: 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b prev 000000000000000008bb407830bac5af6185e24a138f74b7be1bf64f45baf17a
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:508 - Block forks the chain at height 371308/block 000000000000000001953a15026db0a764d4c0c02c4db55f2d00c5d7b19e004a, but it did not cause a reorganize:
000000000000000008bb407830bac5af6185e24a138f74b7be1bf64f45baf17a
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:818 - Connected orphan 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:487 - Block is causing a re-organize
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:642 - Re-organize after split at height 371308
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:643 - Old chain head: 00000000000000001109528a9e5b1d6ded0c55de68fe17830ec71525b358a72b
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:644 - New chain head: 000000000000000001dbe5e129cb808b8de92abc35fae482febaf6e97acadb5b
2015-08-24 13:13:56.289 INFO  [NioClientManager] AbstractBlockChain:645 - Split at block: 000000000000000001953a15026db0a764d4c0c02c4db55f2d00c5d7b19e004a
2015-08-24 13:13:56.296 WARN  [NioClientManager] PeerSocketHandler:230 - [127.0.0.1]:8333 - : java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161) [guava-16.0.1.jar:]
	at org.bitcoinj.core.Wallet.reorganize(Wallet.java:4089) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:688) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:521) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:414) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.tryConnectingOrphans(AbstractBlockChain.java:819) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:418) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:308) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:165) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:945) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.Peer.processMessage(Peer.java:342) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.13.1.jar:]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.13.1.jar:]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-16.0.1.jar:]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) [guava-16.0.1.jar:]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) [bitcoinj-core-0.13.1.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]

2015-08-24 13:13:56.327 INFO  [NioClientManager] PeerGroup:1454 - [127.0.0.1]:8333: Peer died      (0 connected, 0 pending, 1 max)
```

**Comment by mikehearn** [comment]
That assert is much the same as the first one. Are you sure this is the first error printed? It still looks a lot like something died further inside a reorg and then it couldn't recover.

**Comment by jdojff** [comment]
Apart from this warning (13 hours before), the log is clean from errors.
```
2015-08-24 00:23:48.397 WARN  [NioClientManager] Threading$UserThread:121 - User thread has 10000 pending tasks, memory exhaustion may occur.
If you see this message, check your memory consumption and see if it's problematic or excessively spikey.
If it is, check for deadlocked or slow event handlers. If it isn't, try adjusting the constant 
Threading.UserThread.WARNING_THRESHOLD upwards until it's a suitable level for your app, or Integer.MAX_VALUE to disable.
2015-08-24 00:23:53.420 INFO  [Wallet autosave thread] WalletFiles:86 - Background saving wallet, last seen block is 371233/00000000000000001177c35bb84cfed8a406b47b839e85476f77917d7aff948a
2015-08-24 00:23:56.205 INFO  [Wallet autosave thread] WalletFiles:118 - Save completed in 2785msec
2015-08-24 00:28:44.742 WARN  [NioClientManager] Threading$UserThread:121 - User thread has 10000 pending tasks, memory exhaustion may occur.
If you see this message, check your memory consumption and see if it's problematic or excessively spikey.
If it is, check for deadlocked or slow event handlers. If it isn't, try adjusting the constant 
Threading.UserThread.WARNING_THRESHOLD upwards until it's a suitable level for your app, or Integer.MAX_VALUE to disable.
```

**Comment by pmprete** [comment]
Same happened to me using version 14.4 me on block `540801` with  hash `0000000000000000001b934f570a5a225aa47f7f127ec13456e0871ec10b9a8f` 
I tryed debugging the problem and i found out that the First time it enters:
`public void reorganize(StoredBlock splitPoint, List<StoredBlock> oldBlocks, List<StoredBlock> newBlocks)`  on `Wallet.java` 
It pased the check `Preconditions.checkState(this.confidenceChanged.size() == 0);` 
But at some point arround 
```  label305:
                        while(var26.hasNext()) {
                            Sha256Hash blockHash = (Sha256Hash)var26.next();
                            Iterator var30 = mapBlockTx.get(blockHash).iterator();

                            while(true) {
                                while(true) {
                                    if (!var30.hasNext()) {
                                        continue label305;
                                    }

                                    Wallet.TxOffsetPair pair = (Wallet.TxOffsetPair)var30.next();
                                    Transaction tx = pair.tx;
```
After `Iterator var30 = mapBlockTx.get(blockHash).iterator();` i lose the thread execution. 
And then it re enters 
`public void reorganize(StoredBlock splitPoint, List<StoredBlock> oldBlocks, List<StoredBlock> newBlocks) `
But this time, `Preconditions.checkState(this.confidenceChanged.size() == 0);` 
Throws the exception as it has 23 items on confidenceChanged.
