### ISSUE TITLE
Unable to continue downloading block chain - block does not connect and blockChainDownloadLocked loop

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#979]
Originally reported on Google Code with ID 613

```
I've been successfully downloading and updating the blockchain into the local postgres
blockstore for the past several months, however on March 23, 2015 the download has
gotten stuck into a loop and cannot progress. When the download first starts there
is a massive exception log of this error:



at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:285) ~[bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.core.Peer.processBlock(Peer.java:851) [bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.core.Peer.processMessage(Peer.java:351) [bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:139) [bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217) [bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:75) [bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:111) [bitcoinj-core-0.12.2.jar:na]
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
[guava-16.0.1.jar:na]
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) [guava-16.0.1.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_02]
Caused by: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data
    at org.bitcoinj.script.Script.executeScript(Script.java:1007) ~[bitcoinj-core-0.12.2.jar:na]
    at org.bitcoinj.script.Script.correctlySpends(Script.java:1409) ~[bitcoinj-core-0.12.2.jar:na]




And afterwards my logs are filled with these messages looping:



2015-03-26 07:39:00,015 INFO  [NioClientManager] org.bitcoinj.core.MemoryPool - [79.112.73.126]:8333:
Peer announced new transaction [1] 06d32a7860257a1fc52022888bdcd3c9ad1b865fd5b4a643652e5c320c02b045
2015-03-26 07:39:00,270 INFO  [NioClientManager] org.bitcoinj.core.MemoryPool - [95.145.134.174]:8333:
Peer announced new transaction [1] 6346c9079812efbcd36fd6e3852930f4f41f5c129850256ca398b257ba22b595
2015-03-26 07:39:00,528 INFO  [NioClientManager] org.bitcoinj.core.MemoryPool - [79.112.73.126]:8333:
Peer announced new transaction [1] 3b426ac0ee9ae5cf5599e321d3f67ab178bc0ce3ae6de1028a9e4e46daa39887
2015-03-26 07:39:00,929 WARN  [NioClientManager] org.bitcoinj.core.AbstractBlockChain
- Block does not connect: 000000000000000009f3bf474c21742106efc5da4c7cc1aecc7a184d256c82b5
prev 0000000000000000112ef7c396cc72541e794a144218a0b66923f7f9dcd2a166
2015-03-26 07:39:00,929 INFO  [NioClientManager] org.bitcoinj.core.Peer - blockChainDownloadLocked(0000000000000000172f441439ace35799721945867769640b9398f7ae60d192):
ignoring duplicated request
2015-03-26 07:39:01,005 INFO  [NioClientManager] org.bitcoinj.core.MemoryPool - [82.216.224.36]:8333:
Peer announced new transaction [1] f2653cb502816ba31fe30a70479e274feb63a50df8b9370784d74182fd53d7fb
2015-03-26 07:39:01,387 WARN  [NioClientManager] org.bitcoinj.core.AbstractBlockChain
- Block does not connect: 0000000000000000169f9d6b9962023288432ccb2711434224d77cb0e8f9f535
prev 000000000000000009f3bf474c21742106efc5da4c7cc1aecc7a184d256c82b5
2015-03-26 07:39:01,388 INFO  [NioClientManager] org.bitcoinj.core.Peer - blockChainDownloadLocked(0000000000000000172f441439ace35799721945867769640b9398f7ae60d192):
ignoring duplicated request
2015-03-26 07:39:01,563 WARN  [NioClientManager] org.bitcoinj.core.AbstractBlockChain
- Block does not connect: 000000000000000003dc3e8d137716c0ce9c1d599512d874a6135568b1abe692
prev 0000000000000000169f9d6b9962023288432ccb2711434224d77cb0e8f9f535
2015-03-26 07:39:01,564 INFO  [NioClientManager] org.bitcoinj.core.Peer - blockChainDownloadLocked(0000000000000000172f441439ace35799721945867769640b9398f7ae60d192):
ignoring duplicated request
2015-03-26 07:39:01,566 WARN  [NioClientManager] org.bitcoinj.core.AbstractBlockChain
- Block does not connect: 000000000000000016ddc020ac30302355f3db6e1e05ada9302391f367f6ce49
prev 000000000000000003dc3e8d137716c0ce9c1d599512d874a6135568b1abe692
2015-03-26 07:39:01,566 INFO  [NioClientManager] org.bitcoinj.core.Peer - blockChainDownloadLocked(0000000000000000172f441439ace35799721945867769640b9398f7ae60d192):
ignoring duplicated request



I'm using the latest version 0.12.2. In my Postgres database, is there any way I can
roll back the blockchain to a day before this happened to try to proceed normally?
In my 'headers' row I am stuck on row 348882.. Does that determine where to start downloading?
Can i delete some rows from this table to roll back the block chain location?
```

Reported by `FateFree` on 2015-03-26 11:45:40

**Comment by PavelNiedoba** [comment]
I'm seeing similar stack trace in 0.14-SNAPSHOT.  I'm using SPVblockstore. I had Wallet up and running for 3 days, but then blockchain stopped updating. I deleted SPV file, I did restore Wallet from seed and restarted it. Blockchain download stopped at about same block.

[NioClientManager] WARN org.bitcoinj.core.AbstractBlockChain - Block does not connect: 000000000000000004a48cf8b6d8d3b550946b5faffdce0fb5e18a479f70eef6 prev 0000000000000000064c2d5b09b705c082e1eb5528b8364ee907768a5e56cb1a
[NioClientManager] INFO org.bitcoinj.core.Peer - blockChainDownloadLocked(000000000000000004fa4490454077d314c4e17dd00146ccf1eea3ab825c501c): ignoring duplicated request: 000000000000000005a738e8a1622364608cfe899108699d7fd2e6ddb2139116
[NioClientManager] INFO org.bitcoinj.core.Peer - java.lang.Throwable
        at org.bitcoinj.core.Peer.blockChainDownloadLocked(Peer.java:1410)
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1079)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:450)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35)
        at java.lang.Thread.run(Thread.java:745)

**Comment by schildbach** [comment]
@PavelNiedoba "Block does not connect" messages are not a bad thing on its own, afaik. There are many reasons why the blockchain can stop updating -- including a malfunctioning bitcoind. You could try reproducing this problem by connecting to an own bitcoind only. If it fails again, please open a separate issue including logs of both bitcoinj and bitcoind.

Actually I think we should close _this_ issue. It's outdated.
