### ISSUE TITLE
Block too far in future: 1433871841 vs 1433871840

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#987]
Originally reported on Google Code with ID 621
```

Hi,

I'm getting this message from time to time.
The block is ignored but the connection to the peer is kept alive.
All following blocks will not connect and my wallet will not progress.

What should I do about it?
What is the root cause?

Note that the difference is only 1 second.

I use 0.12.3 testnet

Thanks

Offer


INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :000000000001820a23089f55d659cb9b94801f0ba6d8b797a4baa4ee13d07e38 prev: 0000000000017d750b40e85f5ce397741091fda13d291d9cd0314eb17922fd01
block time: 1433870595 time now 1433864297
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :00000000000083e200c506c3cee4960c60eba72c2d9074604bf2470ca664d361 prev: 000000000001820a23089f55d659cb9b94801f0ba6d8b797a4baa4ee13d07e38
block time: 1433871517 time now 1433864339
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :000000000002762d9054db878cf86cba5819a5531bbf0c36cecb163ec272bb14 prev: 00000000000083e200c506c3cee4960c60eba72c2d9074604bf2470ca664d361
block time: 1433870610 time now 1433864373
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :0000000000022cedf56727a544f77d40efdb046594df999ba48541356504ca49 prev: 000000000002762d9054db878cf86cba5819a5531bbf0c36cecb163ec272bb14
block time: 1433870643 time now 1433864419
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :00000000000245423eeada7d7e602980d1cb4a069579831da10dc9a629ea5aac prev: 0000000000022cedf56727a544f77d40efdb046594df999ba48541356504ca49
block time: 1433870612 time now 1433864499
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :000000000001ed211b9edad2bb19c51060ba15b551d3b4a0d73a50c0fed509ce prev: 00000000000245423eeada7d7e602980d1cb4a069579831da10dc9a629ea5aac
block time: 1433871774 time now 1433864575
ERROR: org.bitcoinj.core.AbstractBlockChain - Failed to verify block: 
org.bitcoinj.core.VerificationException: Block too far in future: 1433871841 vs 1433871840
	at org.bitcoinj.core.Block.checkTimestamp(Block.java:673)
	at org.bitcoinj.core.Block.verifyHeader(Block.java:782)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:397)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:304)
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:151)
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:955)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:335)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:178)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:75)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:111)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Unknown Source)
ERROR: org.bitcoinj.core.AbstractBlockChain - 0000000095feafa7c90f93083675f105e06aec07bdb051322a4da63b0e0275da
WARN : org.bitcoinj.core.Peer - [172.241.225.120]:18333: FilteredBlock verification
failed
org.bitcoinj.core.VerificationException: Could not verify block 0000000095feafa7c90f93083675f105e06aec07bdb051322a4da63b0e0275da
FilteredBlock{merkleTree=PartialMerkleTree{transactionCount=2, matchedChildBits=[0],
hashes=[fd6e4db4611af4f51c929cfe725ec4ea0dfb5118e7d8e5f21955f092f3d03e03]}, header=v3
block: 
   previous block: 00000000000360c92ae8b2ce91246bcf37067566e4b8cc5c5652eccc22601e32
   merkle root: fd6e4db4611af4f51c929cfe725ec4ea0dfb5118e7d8e5f21955f092f3d03e03
   time: [1433871841] 2015-06-09T17:44:01Z
   difficulty target (nBits): 486604799
   nonce: 1707745043
}
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:315)
	at org.bitcoinj.core.BlockChain.add(BlockChain.java:151)
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:955)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:335)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:178)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:75)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:111)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bitcoinj.core.VerificationException: Block too far in future: 1433871841
vs 1433871840
	at org.bitcoinj.core.Block.checkTimestamp(Block.java:673)
	at org.bitcoinj.core.Block.verifyHeader(Block.java:782)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:397)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:304)
	... 10 more
WARN : org.bitcoinj.core.AbstractBlockChain - Block does not connect: 000000000000512b11a3b7b9d7082f2d2f95896d329b9436f754e5667292e731
prev 0000000095feafa7c90f93083675f105e06aec07bdb051322a4da63b0e0275da
INFO : com.sonetra.bank.BitcoinjThread - new block downloaded from [172.241.225.120]:18333
block :00000000000360c92ae8b2ce91246bcf37067566e4b8cc5c5652eccc22601e32 prev: 00000000000245423eeada7d7e602980d1cb4a069579831da10dc9a629ea5aac
block time: 1433870639 time now 1433864643
WARN : org.bitcoinj.core.AbstractBlockChain - Block does not connect: 0000000014b2c878e8b6262ff94cdcc7d46b3c5df571dc43cdbb8f7208b1d711
prev 000000000000512b11a3b7b9d7082f2d2f95896d329b9436f754e5667292e731
WARN : org.bitcoinj.core.AbstractBlockChain - Block does not connect: 000000000000984583b8c9cb773a12f27e719a661c3f2d282c84b27dc54759e2
prev 0000000014b2c878e8b6262ff94cdcc7d46b3c5df571dc43cdbb8f7208b1d711
WARN : org.bitcoinj.core.AbstractBlockChain - Block does not connect: 0000000024121f30c0caf3eac84f112c5589a8a1b817073c2f8a44d24695fd6b
prev 000000000000984583b8c9cb773a12f27e719a661c3f2d282c84b27dc54759e2
```

Reported by `offerm` on 2015-06-09 16:10:57

**Comment by mikehearn** [comment]
This has been resolved over on Google Code as notabug
